//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.PrintView.Abstractions.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.PrintView.Abstractions.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert Html to Pdf: &apos;{0}&apos; (exit code is &apos;{1}&apos;)..
        /// </summary>
        internal static string CannotConvertHtmlToPdf {
            get {
                return ResourceManager.GetString("CannotConvertHtmlToPdf", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot convert Html to Pdf: Timeout..
        /// </summary>
        internal static string CannotConvertHtmlToPdfByTimeout {
            get {
                return ResourceManager.GetString("CannotConvertHtmlToPdfByTimeout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize type &apos;{0}&apos;..
        /// </summary>
        internal static string CannotDeserializeTypeError {
            get {
                return ResourceManager.GetString("CannotDeserializeTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not execute command &apos;{0}&apos; with arguments &apos;{1}&apos;. Error: &apos;{2}&apos;..
        /// </summary>
        internal static string CannotExecuteCommand {
            get {
                return ResourceManager.GetString("CannotExecuteCommand", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compilation expression &apos;{0}&apos; completed with exception &apos;{1}&apos;..
        /// </summary>
        internal static string CompilationError {
            get {
                return ResourceManager.GetString("CompilationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal expression: &apos;{0}&apos;..
        /// </summary>
        internal static string IllegalExpression {
            get {
                return ResourceManager.GetString("IllegalExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EAN13.
        /// </summary>
        internal static string PrintBarcodeEan13 {
            get {
                return ResourceManager.GetString("PrintBarcodeEan13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to QR.
        /// </summary>
        internal static string PrintBarcodeQr {
            get {
                return ResourceManager.GetString("PrintBarcodeQr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string PrintBold {
            get {
                return ResourceManager.GetString("PrintBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string PrintDocument {
            get {
                return ResourceManager.GetString("PrintDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink.
        /// </summary>
        internal static string PrintHyperlink {
            get {
                return ResourceManager.GetString("PrintHyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string PrintImage {
            get {
                return ResourceManager.GetString("PrintImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string PrintItalic {
            get {
                return ResourceManager.GetString("PrintItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string PrintLine {
            get {
                return ResourceManager.GetString("PrintLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineBreak.
        /// </summary>
        internal static string PrintLineBreak {
            get {
                return ResourceManager.GetString("PrintLineBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string PrintList {
            get {
                return ResourceManager.GetString("PrintList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageBreak.
        /// </summary>
        internal static string PrintPageBreak {
            get {
                return ResourceManager.GetString("PrintPageBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        internal static string PrintParagraph {
            get {
                return ResourceManager.GetString("PrintParagraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string PrintRun {
            get {
                return ResourceManager.GetString("PrintRun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string PrintSection {
            get {
                return ResourceManager.GetString("PrintSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span.
        /// </summary>
        internal static string PrintSpan {
            get {
                return ResourceManager.GetString("PrintSpan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string PrintStyle {
            get {
                return ResourceManager.GetString("PrintStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string PrintTable {
            get {
                return ResourceManager.GetString("PrintTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cell.
        /// </summary>
        internal static string PrintTableCell {
            get {
                return ResourceManager.GetString("PrintTableCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Column.
        /// </summary>
        internal static string PrintTableColumn {
            get {
                return ResourceManager.GetString("PrintTableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Row.
        /// </summary>
        internal static string PrintTableRow {
            get {
                return ResourceManager.GetString("PrintTableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string PrintUnderline {
            get {
                return ResourceManager.GetString("PrintUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File format &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string PrintViewFileFormatIsNotSupported {
            get {
                return ResourceManager.GetString("PrintViewFileFormatIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Microsoft/msbuild/issues/1661.
        /// </summary>
        internal static string RESOURCE_KEY_FOR_DOTNET_BUILD {
            get {
                return ResourceManager.GetString("RESOURCE_KEY_FOR_DOTNET_BUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown type &apos;{0}&apos;..
        /// </summary>
        internal static string UnknownType {
            get {
                return ResourceManager.GetString("UnknownType", resourceCulture);
            }
        }
    }
}
