//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace InfinniPlatform.MessageQueue.Properties {
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.MessageQueue.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started ack of message..
        /// </summary>
        internal static string AckStart {
            get {
                return ResourceManager.GetString("AckStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded ack of message..
        /// </summary>
        internal static string AckSuccess {
            get {
                return ResourceManager.GetString("AckSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Started consume of message..
        /// </summary>
        internal static string ConsumeStart {
            get {
                return ResourceManager.GetString("ConsumeStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Succeeded consume of message..
        /// </summary>
        internal static string ConsumeSuccess {
            get {
                return ResourceManager.GetString("ConsumeSuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization of broadcast consumers successfully completed..
        /// </summary>
        internal static string InitializationOfBroadcastConsumersSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("InitializationOfBroadcastConsumersSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization of the broadcast consumer started..
        /// </summary>
        internal static string InitializationOfBroadcastConsumerStarted {
            get {
                return ResourceManager.GetString("InitializationOfBroadcastConsumerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization of the broadcast consumer successfully completed..
        /// </summary>
        internal static string InitializationOfBroadcastConsumerSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("InitializationOfBroadcastConsumerSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization of consumers started..
        /// </summary>
        internal static string InitializationOfConsumersStarted {
            get {
                return ResourceManager.GetString("InitializationOfConsumersStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization of task consumers successfully completed..
        /// </summary>
        internal static string InitializationOfTaskConsumersSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("InitializationOfTaskConsumersSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization of the task consumer started..
        /// </summary>
        internal static string InitializationOfTaskConsumerStarted {
            get {
                return ResourceManager.GetString("InitializationOfTaskConsumerStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Initialization of the task consumer successfully completed..
        /// </summary>
        internal static string InitializationOfTaskConsumerSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("InitializationOfTaskConsumerSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to https://github.com/Microsoft/msbuild/issues/1661.
        /// </summary>
        internal static string RESOURCE_KEY_FOR_DOTNET_BUILD {
            get {
                return ResourceManager.GetString("RESOURCE_KEY_FOR_DOTNET_BUILD", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create RabbitMQ channel..
        /// </summary>
        internal static string UnableToCreateRabbitMQChannel {
            get {
                return ResourceManager.GetString("UnableToCreateRabbitMQChannel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get queue name..
        /// </summary>
        internal static string UnableToGetQueueName {
            get {
                return ResourceManager.GetString("UnableToGetQueueName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to initialize consumers..
        /// </summary>
        internal static string UnableToInitializeConsumers {
            get {
                return ResourceManager.GetString("UnableToInitializeConsumers", resourceCulture);
            }
        }
    }
}
