//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.Authentication.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.Authentication.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active role cannot be null or whitespace..
        /// </summary>
        internal static string ActiveRoleCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ActiveRoleCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ADFS server name cannot be null or whitespace..
        /// </summary>
        internal static string AuthenticationActiveDirectoryAdfsServerNameCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("AuthenticationActiveDirectoryAdfsServerNameCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESIA Client ID cannot be null or whitespace..
        /// </summary>
        internal static string AuthenticationEsiaClientIdCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("AuthenticationEsiaClientIdCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESIA Client Secret Certificate cannot be null or whitespace..
        /// </summary>
        internal static string AuthenticationEsiaClientSecretCertCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("AuthenticationEsiaClientSecretCertCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ESIA server cannot be null or whitespace..
        /// </summary>
        internal static string AuthenticationEsiaServerCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("AuthenticationEsiaServerCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Client ID cannot be null or whitespace..
        /// </summary>
        internal static string AuthenticationFacebookClientIdCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("AuthenticationFacebookClientIdCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Facebook Client Secret cannot be null or whitespace..
        /// </summary>
        internal static string AuthenticationFacebookClientSecretCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("AuthenticationFacebookClientSecretCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Client ID cannot be null or whitespace..
        /// </summary>
        internal static string AuthenticationGoogleClientIdCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("AuthenticationGoogleClientIdCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Google Client Secret cannot be null or whitespace..
        /// </summary>
        internal static string AuthenticationGoogleClientSecretCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("AuthenticationGoogleClientSecretCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AuthenticationManager not found..
        /// </summary>
        internal static string AuthenticationManagerNotFound {
            get {
                return ResourceManager.GetString("AuthenticationManagerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vk Client ID cannot be null or whitespace..
        /// </summary>
        internal static string AuthenticationVkClientIdCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("AuthenticationVkClientIdCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vk Client Secret cannot be null or whitespace..
        /// </summary>
        internal static string AuthenticationVkClientSecretCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("AuthenticationVkClientSecretCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate e-mail: &apos;{0}&apos;..
        /// </summary>
        internal static string DuplicateEmail {
            get {
                return ResourceManager.GetString("DuplicateEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate phone number: &apos;{0}&apos;..
        /// </summary>
        internal static string DuplicatePhoneNumber {
            get {
                return ResourceManager.GetString("DuplicatePhoneNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Duplicate username: &apos;{0}&apos;..
        /// </summary>
        internal static string DuplicateUserName {
            get {
                return ResourceManager.GetString("DuplicateUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External provider cannot be null or whitespace..
        /// </summary>
        internal static string ExternalProviderCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ExternalProviderCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to External provider key cannot be null or whitespace..
        /// </summary>
        internal static string ExternalProviderKeyCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ExternalProviderKeyCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Failure URL cannot be null or whitespace..
        /// </summary>
        internal static string FailureUrlCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("FailureUrlCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid e-mail: &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidEmail {
            get {
                return ResourceManager.GetString("InvalidEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username: &apos;{0}&apos;..
        /// </summary>
        internal static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password..
        /// </summary>
        internal static string InvalidUsernameOrPassword {
            get {
                return ResourceManager.GetString("InvalidUsernameOrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New password cannot be null or whitespace..
        /// </summary>
        internal static string NewPasswordCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("NewPasswordCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request is not authenticated..
        /// </summary>
        internal static string RequestIsNotAuthenticated {
            get {
                return ResourceManager.GetString("RequestIsNotAuthenticated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Success URL cannot be null or whitespace..
        /// </summary>
        internal static string SuccessUrlCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("SuccessUrlCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsuccessful signin with external provider..
        /// </summary>
        internal static string UnsuccessfulSignInWithExternalProvider {
            get {
                return ResourceManager.GetString("UnsuccessfulSignInWithExternalProvider", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserId not found..
        /// </summary>
        internal static string UserIdNotFound {
            get {
                return ResourceManager.GetString("UserIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User is not in the role &apos;{0}&apos;..
        /// </summary>
        internal static string UserIsNotInRole {
            get {
                return ResourceManager.GetString("UserIsNotInRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserManager not found. Register IApplicationUserStore..
        /// </summary>
        internal static string UserManagerNotFound {
            get {
                return ResourceManager.GetString("UserManagerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot be null or whitespace..
        /// </summary>
        internal static string UserNameCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("UserNameCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User not found..
        /// </summary>
        internal static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
    }
}
