//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.Esia.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.Esia.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication failed..
        /// </summary>
        internal static string AuthenticationFailed {
            get {
                return ResourceManager.GetString("AuthenticationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CallbackPath cannot be null or white space..
        /// </summary>
        internal static string CallbackPathCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("CallbackPathCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate &apos;{0}&apos; does not have a private key..
        /// </summary>
        internal static string CertificateDoesNotHavePrivateKey {
            get {
                return ResourceManager.GetString("CertificateDoesNotHavePrivateKey", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Certificate &apos;{0}&apos; not found..
        /// </summary>
        internal static string CertificateNotFound {
            get {
                return ResourceManager.GetString("CertificateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientId cannot be null or white space..
        /// </summary>
        internal static string ClientIdCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ClientIdCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ClientSecretCert cannot be null or white space..
        /// </summary>
        internal static string ClientSecretCertCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ClientSecretCertCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not create hash algorithm object. Certificate: &apos;{0}&apos;, hash algorithm: {1}..
        /// </summary>
        internal static string CreateHashAlgorithmFailed {
            get {
                return ResourceManager.GetString("CreateHashAlgorithmFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;RelayState&apos; is not found in the response from ESIA..
        /// </summary>
        internal static string RelayStateNotFound {
            get {
                return ResourceManager.GetString("RelayStateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Parameter &apos;SAMLResponse&apos; is not found in the response from ESIA..
        /// </summary>
        internal static string SamlResponseNotFound {
            get {
                return ResourceManager.GetString("SamlResponseNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authentication server cannot be null or white space..
        /// </summary>
        internal static string ServerCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ServerCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SignatureDescription could not be created for the signature algorithm supplied. Certificate: &apos;{0}&apos;, signature algorithm: {1}..
        /// </summary>
        internal static string SignatureDescriptionNotCreated {
            get {
                return ResourceManager.GetString("SignatureDescriptionNotCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid return state, unable to redirect..
        /// </summary>
        internal static string UnableToRedirect {
            get {
                return ResourceManager.GetString("UnableToRedirect", resourceCulture);
            }
        }
    }
}
