//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.FastReport.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.FastReport.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A circular reference on &apos;{0}&apos; was detected while analyzing property &apos;{1}&apos;..
        /// </summary>
        internal static string CircularReferenceWasDetected {
            get {
                return ResourceManager.GetString("CircularReferenceWasDetected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The collection &apos;{0}&apos; has no data schema of items..
        /// </summary>
        internal static string CollectionHasNoDataSchemaOfItems {
            get {
                return ResourceManager.GetString("CollectionHasNoDataSchemaOfItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve schema for collection &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotResolveSchemaForCollection {
            get {
                return ResourceManager.GetString("CouldNotResolveSchemaForCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve schema for property &apos;{0}&apos;..
        /// </summary>
        internal static string CouldNotResolveSchemaForProperty {
            get {
                return ResourceManager.GetString("CouldNotResolveSchemaForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve schema reference &apos;{0}&apos; for collection &apos;{1}&apos;..
        /// </summary>
        internal static string CouldNotResolveSchemaReferenceForCollection {
            get {
                return ResourceManager.GetString("CouldNotResolveSchemaReferenceForCollection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not resolve schema reference &apos;{0}&apos; for property &apos;{1}&apos;..
        /// </summary>
        internal static string CouldNotResolveSchemaReferenceForProperty {
            get {
                return ResourceManager.GetString("CouldNotResolveSchemaReferenceForProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data band should referenced on data source..
        /// </summary>
        internal static string DataBandShouldReferencedOnDataSource {
            get {
                return ResourceManager.GetString("DataBandShouldReferencedOnDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data schema &apos;{0}&apos; is already declared..
        /// </summary>
        internal static string DataSchemaAlreadyDeclared {
            get {
                return ResourceManager.GetString("DataSchemaAlreadyDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source &apos;{0}&apos; already registered..
        /// </summary>
        internal static string DataSourceAlreadyRegistered {
            get {
                return ResourceManager.GetString("DataSourceAlreadyRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; has incorrect format..
        /// </summary>
        internal static string ExpressionHasIncorrectFormat {
            get {
                return ResourceManager.GetString("ExpressionHasIncorrectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; referenced on unknown data source &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionReferencedOnUnknownDataSource {
            get {
                return ResourceManager.GetString("ExpressionReferencedOnUnknownDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; referenced on unknown parameter &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionReferencedOnUnknownParameter {
            get {
                return ResourceManager.GetString("ExpressionReferencedOnUnknownParameter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; referenced on unknown property &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionReferencedOnUnknownProperty {
            get {
                return ResourceManager.GetString("ExpressionReferencedOnUnknownProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; referenced on unknown total &apos;{1}&apos;..
        /// </summary>
        internal static string ExpressionReferencedOnUnknownTotal {
            get {
                return ResourceManager.GetString("ExpressionReferencedOnUnknownTotal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression &apos;{0}&apos; should referenced on property..
        /// </summary>
        internal static string ExpressionShouldReferencedOnProperty {
            get {
                return ResourceManager.GetString("ExpressionShouldReferencedOnProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not supported report file format &apos;{0}&apos;..
        /// </summary>
        internal static string NotSupportedReportFileFormat {
            get {
                return ResourceManager.GetString("NotSupportedReportFileFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The object &apos;{0}&apos; should have at least one property..
        /// </summary>
        internal static string ObjectShouldHaveAtLeastOneProperty {
            get {
                return ResourceManager.GetString("ObjectShouldHaveAtLeastOneProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; has no data schema..
        /// </summary>
        internal static string PropertyHasNoDataSchema {
            get {
                return ResourceManager.GetString("PropertyHasNoDataSchema", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property path &apos;{0}&apos; is incorrect..
        /// </summary>
        internal static string PropertyPathIsIncorrect {
            get {
                return ResourceManager.GetString("PropertyPathIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The property &apos;{0}&apos; should be of type &apos;Object&apos;..
        /// </summary>
        internal static string PropertyShouldBeOfTypeObject {
            get {
                return ResourceManager.GetString("PropertyShouldBeOfTypeObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report object &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string ReportObjectIsNotSupported {
            get {
                return ResourceManager.GetString("ReportObjectIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sort field &apos;{0}&apos; should referenced on data source &apos;{1}&apos;..
        /// </summary>
        internal static string SortFieldShouldReferencedOnDataSource {
            get {
                return ResourceManager.GetString("SortFieldShouldReferencedOnDataSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Total &apos;{0}&apos; already registered..
        /// </summary>
        internal static string TotalAlreadyRegistered {
            get {
                return ResourceManager.GetString("TotalAlreadyRegistered", resourceCulture);
            }
        }
    }
}
