//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.Sdk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.Sdk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There an business logic error on request execution..
        /// </summary>
        internal static string BusinessLogicError {
            get {
                return ResourceManager.GetString("BusinessLogicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get acl list with selected aclType: {0}.
        /// </summary>
        internal static string CantGetAclListForSpecifiedType {
            get {
                return ResourceManager.GetString("CantGetAclListForSpecifiedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document to detach should not be null..
        /// </summary>
        internal static string DocumentToDetachShouldntBeEmpty {
            get {
                return ResourceManager.GetString("DocumentToDetachShouldntBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an internal server error..
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote server not found..
        /// </summary>
        internal static string RemoteServerNotFound {
            get {
                return ResourceManager.GetString("RemoteServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query result is not of array type.
        /// </summary>
        internal static string ResultIsNotOfArrayType {
            get {
                return ResourceManager.GetString("ResultIsNotOfArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query result is not of object type.
        /// </summary>
        internal static string ResultIsNotOfObjectType {
            get {
                return ResourceManager.GetString("ResultIsNotOfObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not registered! Please check type of request (GET,POST) and name of invoked service instance..
        /// </summary>
        internal static string ServiceNotRegistered {
            get {
                return ResourceManager.GetString("ServiceNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not service on specified url.
        /// </summary>
        internal static string ServiceNotRegisteredError {
            get {
                return ResourceManager.GetString("ServiceNotRegisteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client session not initialized..
        /// </summary>
        internal static string SessionNotInitialized {
            get {
                return ResourceManager.GetString("SessionNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add role with exception:{0}.
        /// </summary>
        internal static string UnableToAddRole {
            get {
                return ResourceManager.GetString("UnableToAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add user with exception: {0}.
        /// </summary>
        internal static string UnableToAddUser {
            get {
                return ResourceManager.GetString("UnableToAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add user claim with exception: {0}.
        /// </summary>
        internal static string UnableToAddUserClaim {
            get {
                return ResourceManager.GetString("UnableToAddUserClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add role to user with exception: {0}.
        /// </summary>
        internal static string UnableToAddUserRole {
            get {
                return ResourceManager.GetString("UnableToAddUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to attach document to session with exception: {0}.
        /// </summary>
        internal static string UnableToAttachDocumentToSession {
            get {
                return ResourceManager.GetString("UnableToAttachDocumentToSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to attach file to session with exception: {0}.
        /// </summary>
        internal static string UnableToAttachFileToSession {
            get {
                return ResourceManager.GetString("UnableToAttachFileToSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password for user with exception: {0}.
        /// </summary>
        internal static string UnableToChangePasswordUser {
            get {
                return ResourceManager.GetString("UnableToChangePasswordUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to commit session with exception: {0}.
        /// </summary>
        internal static string UnableToCommitException {
            get {
                return ResourceManager.GetString("UnableToCommitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create new session..
        /// </summary>
        internal static string UnableToCreateNewSession {
            get {
                return ResourceManager.GetString("UnableToCreateNewSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete document with exception: {0}.
        /// </summary>
        internal static string UnableToDeleteDocument {
            get {
                return ResourceManager.GetString("UnableToDeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete role with exception: {0}.
        /// </summary>
        internal static string UnableToDeleteRole {
            get {
                return ResourceManager.GetString("UnableToDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete user with exception: {0}.
        /// </summary>
        internal static string UnableToDeleteUser {
            get {
                return ResourceManager.GetString("UnableToDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete user role with exception: {0}.
        /// </summary>
        internal static string UnableToDeleteUserRole {
            get {
                return ResourceManager.GetString("UnableToDeleteUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detach document from session with exception: {0}.
        /// </summary>
        internal static string UnableToDetachDocument {
            get {
                return ResourceManager.GetString("UnableToDetachDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detach file from session with exception: {0}.
        /// </summary>
        internal static string UnableToDetachFileFromSession {
            get {
                return ResourceManager.GetString("UnableToDetachFileFromSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download file from server with exception: {0}.
        /// </summary>
        internal static string UnableToDownloadFileFromServer {
            get {
                return ResourceManager.GetString("UnableToDownloadFileFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get document with exception: {0}.
        /// </summary>
        internal static string UnableToGetDocument {
            get {
                return ResourceManager.GetString("UnableToGetDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get session with exception: {0}.
        /// </summary>
        internal static string UnableToGetSession {
            get {
                return ResourceManager.GetString("UnableToGetSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get user with exception: {0}.
        /// </summary>
        internal static string UnableToGetUser {
            get {
                return ResourceManager.GetString("UnableToGetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get user claim with exception: {0}.
        /// </summary>
        internal static string UnableToGetUserClaim {
            get {
                return ResourceManager.GetString("UnableToGetUserClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to grant access to user with exception: {0}.
        /// </summary>
        internal static string UnableToGrantAccessToUser {
            get {
                return ResourceManager.GetString("UnableToGrantAccessToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove session with exception: {0}.
        /// </summary>
        internal static string UnableToRemoveSession {
            get {
                return ResourceManager.GetString("UnableToRemoveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove user claim with exception:{0}.
        /// </summary>
        internal static string UnableToRemoveUserClaim {
            get {
                return ResourceManager.GetString("UnableToRemoveUserClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set document with exception: {0}.
        /// </summary>
        internal static string UnableToSetDocument {
            get {
                return ResourceManager.GetString("UnableToSetDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sign in user with exception: {0}.
        /// </summary>
        internal static string UnableToSignInUser {
            get {
                return ResourceManager.GetString("UnableToSignInUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sign out user with exception: {0}.
        /// </summary>
        internal static string UnableToSignOutUser {
            get {
                return ResourceManager.GetString("UnableToSignOutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sign in user with exception: {0}.
        /// </summary>
        internal static string UnableToSignUser {
            get {
                return ResourceManager.GetString("UnableToSignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update document with exception: {0}.
        /// </summary>
        internal static string UnableToUpdateDocument {
            get {
                return ResourceManager.GetString("UnableToUpdateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to upload file on server with exception: {0}.
        /// </summary>
        internal static string UnableToUploadFileOnServer {
            get {
                return ResourceManager.GetString("UnableToUploadFileOnServer", resourceCulture);
            }
        }
    }
}
