//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18408
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.Sdk.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.Sdk.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There an business logic error on request execution..
        /// </summary>
        internal static string BusinessLogicError {
            get {
                return ResourceManager.GetString("BusinessLogicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get acl list with selected aclType: {0}.
        /// </summary>
        internal static string CantGetAclListForSpecifiedType {
            get {
                return ResourceManager.GetString("CantGetAclListForSpecifiedType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection can not be modified.
        /// </summary>
        internal static string CollectionCanNotBeModified {
            get {
                return ResourceManager.GetString("CollectionCanNotBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document to detach should not be null..
        /// </summary>
        internal static string DocumentToDetachShouldntBeEmpty {
            get {
                return ResourceManager.GetString("DocumentToDetachShouldntBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to get user applications actual versions with exception &quot;{0}&quot;.
        /// </summary>
        internal static string FailToGetApplicationActualVersions {
            get {
                return ResourceManager.GetString("FailToGetApplicationActualVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to get user irrelevant versions with exception: {0}.
        /// </summary>
        internal static string FailToGetIrrelevantVersions {
            get {
                return ResourceManager.GetString("FailToGetIrrelevantVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to set user application relevant versions with exception &quot;{0}&quot;.
        /// </summary>
        internal static string FailToSetUserRelevantVersions {
            get {
                return ResourceManager.GetString("FailToSetUserRelevantVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is an internal server error..
        /// </summary>
        internal static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property path cannot be null or empty..
        /// </summary>
        internal static string PropertyPathCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("PropertyPathCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote server not found..
        /// </summary>
        internal static string RemoteServerNotFound {
            get {
                return ResourceManager.GetString("RemoteServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query result is not of array type.
        /// </summary>
        internal static string ResultIsNotOfArrayType {
            get {
                return ResourceManager.GetString("ResultIsNotOfArrayType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query result is not of object type.
        /// </summary>
        internal static string ResultIsNotOfObjectType {
            get {
                return ResourceManager.GetString("ResultIsNotOfObjectType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not registered! Please check type of request (GET,POST) and name of invoked service instance..
        /// </summary>
        internal static string ServiceNotRegistered {
            get {
                return ResourceManager.GetString("ServiceNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There is not service on specified url.
        /// </summary>
        internal static string ServiceNotRegisteredError {
            get {
                return ResourceManager.GetString("ServiceNotRegisteredError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Client session not initialized..
        /// </summary>
        internal static string SessionNotInitialized {
            get {
                return ResourceManager.GetString("SessionNotInitialized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target object cannot be null..
        /// </summary>
        internal static string TargetObjectCannotBeNull {
            get {
                return ResourceManager.GetString("TargetObjectCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add role with exception:{0}.
        /// </summary>
        internal static string UnableToAddRole {
            get {
                return ResourceManager.GetString("UnableToAddRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add user with exception: {0}.
        /// </summary>
        internal static string UnableToAddUser {
            get {
                return ResourceManager.GetString("UnableToAddUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add user claim with exception: {0}.
        /// </summary>
        internal static string UnableToAddUserClaim {
            get {
                return ResourceManager.GetString("UnableToAddUserClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to add role to user with exception: {0}.
        /// </summary>
        internal static string UnableToAddUserRole {
            get {
                return ResourceManager.GetString("UnableToAddUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to attach document to session with exception: {0}.
        /// </summary>
        internal static string UnableToAttachDocumentToSession {
            get {
                return ResourceManager.GetString("UnableToAttachDocumentToSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to attach file to session with exception: {0}.
        /// </summary>
        internal static string UnableToAttachFileToSession {
            get {
                return ResourceManager.GetString("UnableToAttachFileToSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to change password for user with exception: {0}.
        /// </summary>
        internal static string UnableToChangePasswordUser {
            get {
                return ResourceManager.GetString("UnableToChangePasswordUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to commit session with exception: {0}.
        /// </summary>
        internal static string UnableToCommitException {
            get {
                return ResourceManager.GetString("UnableToCommitException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to create new session..
        /// </summary>
        internal static string UnableToCreateNewSession {
            get {
                return ResourceManager.GetString("UnableToCreateNewSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete assembly metadata with exception {0}.
        /// </summary>
        internal static string UnableToDeleteAssemblyMetadata {
            get {
                return ResourceManager.GetString("UnableToDeleteAssemblyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete config metadata with exception {0}.
        /// </summary>
        internal static string UnableToDeleteConfigMetadata {
            get {
                return ResourceManager.GetString("UnableToDeleteConfigMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete document with exception: {0}.
        /// </summary>
        internal static string UnableToDeleteDocument {
            get {
                return ResourceManager.GetString("UnableToDeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete document metadata with exception {0}.
        /// </summary>
        internal static string UnableToDeleteDocumentMetadata {
            get {
                return ResourceManager.GetString("UnableToDeleteDocumentMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete menu metadata with exception {0}.
        /// </summary>
        internal static string UnableToDeleteMenuMetadata {
            get {
                return ResourceManager.GetString("UnableToDeleteMenuMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete print view metadata with exception {0}.
        /// </summary>
        internal static string UnableToDeletePrintViewMetadata {
            get {
                return ResourceManager.GetString("UnableToDeletePrintViewMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete service metadata with exception {0}.
        /// </summary>
        internal static string UnableToDeleteProcessMetadata {
            get {
                return ResourceManager.GetString("UnableToDeleteProcessMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete register metadata with exception {0}.
        /// </summary>
        internal static string UnableToDeleteRegisterMetadata {
            get {
                return ResourceManager.GetString("UnableToDeleteRegisterMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete role with exception: {0}.
        /// </summary>
        internal static string UnableToDeleteRole {
            get {
                return ResourceManager.GetString("UnableToDeleteRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete scenario metadata by id with exception {0}.
        /// </summary>
        internal static string UnableToDeleteScenarioMetadata {
            get {
                return ResourceManager.GetString("UnableToDeleteScenarioMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete service metadata with exception {0}.
        /// </summary>
        internal static string UnableToDeleteServiceMetadata {
            get {
                return ResourceManager.GetString("UnableToDeleteServiceMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete solution metadata with exception: {0}.
        /// </summary>
        internal static string UnableToDeleteSolutionMetadata {
            get {
                return ResourceManager.GetString("UnableToDeleteSolutionMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete user with exception: {0}.
        /// </summary>
        internal static string UnableToDeleteUser {
            get {
                return ResourceManager.GetString("UnableToDeleteUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete user role with exception: {0}.
        /// </summary>
        internal static string UnableToDeleteUserRole {
            get {
                return ResourceManager.GetString("UnableToDeleteUserRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete view metadata with exception {0}.
        /// </summary>
        internal static string UnableToDeleteViewMetadaa {
            get {
                return ResourceManager.GetString("UnableToDeleteViewMetadaa", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detach document from session with exception: {0}.
        /// </summary>
        internal static string UnableToDetachDocument {
            get {
                return ResourceManager.GetString("UnableToDetachDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to detach file from session with exception: {0}.
        /// </summary>
        internal static string UnableToDetachFileFromSession {
            get {
                return ResourceManager.GetString("UnableToDetachFileFromSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to download file from server with exception: {0}.
        /// </summary>
        internal static string UnableToDownloadFileFromServer {
            get {
                return ResourceManager.GetString("UnableToDownloadFileFromServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get assembly metadata with exception {0}.
        /// </summary>
        internal static string UnableToGetAssemblyMetadata {
            get {
                return ResourceManager.GetString("UnableToGetAssemblyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get config metadata with exception {0}.
        /// </summary>
        internal static string UnableToGetConfigMetadata {
            get {
                return ResourceManager.GetString("UnableToGetConfigMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get document with exception: {0}.
        /// </summary>
        internal static string UnableToGetDocument {
            get {
                return ResourceManager.GetString("UnableToGetDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get document metadata with exception {0}.
        /// </summary>
        internal static string UnableToGetDocumentMetadata {
            get {
                return ResourceManager.GetString("UnableToGetDocumentMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get menu metadata with exception {0}.
        /// </summary>
        internal static string UnableToGetMenuMetadata {
            get {
                return ResourceManager.GetString("UnableToGetMenuMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get print view metadata with exception {0}.
        /// </summary>
        internal static string UnableToGetPrintViewMetadata {
            get {
                return ResourceManager.GetString("UnableToGetPrintViewMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get service metadata with exception {0}.
        /// </summary>
        internal static string UnableToGetProcessMetadata {
            get {
                return ResourceManager.GetString("UnableToGetProcessMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get register metadata with exception {0}.
        /// </summary>
        internal static string UnableToGetRegisterMetadata {
            get {
                return ResourceManager.GetString("UnableToGetRegisterMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get scenario metadata with exception {0}.
        /// </summary>
        internal static string UnableToGetScenarioMetadata {
            get {
                return ResourceManager.GetString("UnableToGetScenarioMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get service metadata with exception {0}.
        /// </summary>
        internal static string UnableToGetServiceMetadata {
            get {
                return ResourceManager.GetString("UnableToGetServiceMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get session with exception: {0}.
        /// </summary>
        internal static string UnableToGetSession {
            get {
                return ResourceManager.GetString("UnableToGetSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get user with exception: {0}.
        /// </summary>
        internal static string UnableToGetUser {
            get {
                return ResourceManager.GetString("UnableToGetUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get user claim with exception: {0}.
        /// </summary>
        internal static string UnableToGetUserClaim {
            get {
                return ResourceManager.GetString("UnableToGetUserClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to get view metadata with exception {0}.
        /// </summary>
        internal static string UnableToGetViewMetadata {
            get {
                return ResourceManager.GetString("UnableToGetViewMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to grant access to user with exception: {0}.
        /// </summary>
        internal static string UnableToGrantAccessToUser {
            get {
                return ResourceManager.GetString("UnableToGrantAccessToUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert assembly metadata with exception {0}.
        /// </summary>
        internal static string UnableToInsertAssemblyMetadata {
            get {
                return ResourceManager.GetString("UnableToInsertAssemblyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert config metadata with exception {0}.
        /// </summary>
        internal static string UnableToInsertConfigMetadata {
            get {
                return ResourceManager.GetString("UnableToInsertConfigMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert document metadata with exception {0}.
        /// </summary>
        internal static string UnableToInsertDocumentMetadata {
            get {
                return ResourceManager.GetString("UnableToInsertDocumentMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert menu metadata with exception {0}.
        /// </summary>
        internal static string UnableToInsertMenuMetadata {
            get {
                return ResourceManager.GetString("UnableToInsertMenuMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert print view metadata with exception {0}.
        /// </summary>
        internal static string UnableToInsertPrintViewMetadata {
            get {
                return ResourceManager.GetString("UnableToInsertPrintViewMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert service metadata with exception {0}.
        /// </summary>
        internal static string UnableToInsertProcessMetadata {
            get {
                return ResourceManager.GetString("UnableToInsertProcessMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert register metadata with exception {0}.
        /// </summary>
        internal static string UnableToInsertRegisterMetadata {
            get {
                return ResourceManager.GetString("UnableToInsertRegisterMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert scenario metadata with exception {0}.
        /// </summary>
        internal static string UnableToInsertScenarioMetadata {
            get {
                return ResourceManager.GetString("UnableToInsertScenarioMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert service metadata with exception {0}.
        /// </summary>
        internal static string UnableToInsertServiceMetadata {
            get {
                return ResourceManager.GetString("UnableToInsertServiceMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert solution metadata with exception: {0}.
        /// </summary>
        internal static string UnableToInsertSolutionMetadata {
            get {
                return ResourceManager.GetString("UnableToInsertSolutionMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to insert view metadata with exception {0}.
        /// </summary>
        internal static string UnableToInsertViewMetadata {
            get {
                return ResourceManager.GetString("UnableToInsertViewMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to invoke custom user service: {0}.
        /// </summary>
        internal static string UnableToInvokeCustomService {
            get {
                return ResourceManager.GetString("UnableToInvokeCustomService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove session with exception: {0}.
        /// </summary>
        internal static string UnableToRemoveSession {
            get {
                return ResourceManager.GetString("UnableToRemoveSession", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to remove user claim with exception:{0}.
        /// </summary>
        internal static string UnableToRemoveUserClaim {
            get {
                return ResourceManager.GetString("UnableToRemoveUserClaim", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to set document with exception: {0}.
        /// </summary>
        internal static string UnableToSetDocument {
            get {
                return ResourceManager.GetString("UnableToSetDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sign in user with exception: {0}.
        /// </summary>
        internal static string UnableToSignInUser {
            get {
                return ResourceManager.GetString("UnableToSignInUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sign out user with exception: {0}.
        /// </summary>
        internal static string UnableToSignOutUser {
            get {
                return ResourceManager.GetString("UnableToSignOutUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to sign in user with exception: {0}.
        /// </summary>
        internal static string UnableToSignUser {
            get {
                return ResourceManager.GetString("UnableToSignUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update assembly metadata with exception {0}.
        /// </summary>
        internal static string UnableToUpdateAssemblyMetadata {
            get {
                return ResourceManager.GetString("UnableToUpdateAssemblyMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update config metadata with exception {0}.
        /// </summary>
        internal static string UnableToUpdateConfigMetadata {
            get {
                return ResourceManager.GetString("UnableToUpdateConfigMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update document with exception: {0}.
        /// </summary>
        internal static string UnableToUpdateDocument {
            get {
                return ResourceManager.GetString("UnableToUpdateDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update document metadata with exception {0}.
        /// </summary>
        internal static string UnableToUpdateDocumentMetadata {
            get {
                return ResourceManager.GetString("UnableToUpdateDocumentMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update menu metadata with exception {0}.
        /// </summary>
        internal static string UnableToUpdateMenuMetadata {
            get {
                return ResourceManager.GetString("UnableToUpdateMenuMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update printview metadata with exception {0}.
        /// </summary>
        internal static string UnableToUpdatePrintViewMetaata {
            get {
                return ResourceManager.GetString("UnableToUpdatePrintViewMetaata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update service metadata with exception {0}.
        /// </summary>
        internal static string UnableToUpdateProcessMetadata {
            get {
                return ResourceManager.GetString("UnableToUpdateProcessMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update register metadata with exception {0}.
        /// </summary>
        internal static string UnableToUpdateRegisterMetadata {
            get {
                return ResourceManager.GetString("UnableToUpdateRegisterMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update scenario metadata with exception {0}.
        /// </summary>
        internal static string UnableToUpdateScenarioMetadata {
            get {
                return ResourceManager.GetString("UnableToUpdateScenarioMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update service metadata with exception {0}.
        /// </summary>
        internal static string UnableToUpdateServiceMetadata {
            get {
                return ResourceManager.GetString("UnableToUpdateServiceMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update solution metadata with exception {0}.
        /// </summary>
        internal static string UnableToUpdateSolutionMetadata {
            get {
                return ResourceManager.GetString("UnableToUpdateSolutionMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update view metadata with exception {0}.
        /// </summary>
        internal static string UnableToUpdateViewMetadata {
            get {
                return ResourceManager.GetString("UnableToUpdateViewMetadata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to upload file on server with exception: {0}.
        /// </summary>
        internal static string UnableToUploadFileOnServer {
            get {
                return ResourceManager.GetString("UnableToUploadFileOnServer", resourceCulture);
            }
        }
    }
}
