//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.Reporting.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.Reporting.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Accept type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string AcceptTypeIsNotSupported {
            get {
                return ResourceManager.GetString("AcceptTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;ConnectionString&apos; cannot be null or white space..
        /// </summary>
        internal static string ConnectionStringCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ConnectionStringCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data provider cannot be null..
        /// </summary>
        internal static string DataProviderInfoCannotBeNull {
            get {
                return ResourceManager.GetString("DataProviderInfoCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data provider &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string DataProviderIsNotSupported {
            get {
                return ResourceManager.GetString("DataProviderIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data schema cannot be null..
        /// </summary>
        internal static string DataSchemaCannotBeNull {
            get {
                return ResourceManager.GetString("DataSchemaCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source &apos;{0}&apos; not found..
        /// </summary>
        internal static string DataSourceNotFound {
            get {
                return ResourceManager.GetString("DataSourceNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data source &apos;{0}&apos; does not have a data provider..
        /// </summary>
        internal static string DataSourceProviderCannotBeNull {
            get {
                return ResourceManager.GetString("DataSourceProviderCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report template &apos;{0}&apos; not found..
        /// </summary>
        internal static string ReportTemplateNotFound {
            get {
                return ResourceManager.GetString("ReportTemplateNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;RequestUri&apos; cannot be null or white space..
        /// </summary>
        internal static string RequestUriCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("RequestUriCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SQL server type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string SqlServerTypeIsNotSupported {
            get {
                return ResourceManager.GetString("SqlServerTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &apos;ValueProperty&apos; cannot be null or white space..
        /// </summary>
        internal static string ValuePropertyCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ValuePropertyCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
    }
}
