//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.UserInterface.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.UserInterface.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InfinniPlatform: Designer.
        /// </summary>
        internal static string AppViewText {
            get {
                return ResourceManager.GetString("AppViewText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies.
        /// </summary>
        internal static string AssemblyContainer {
            get {
                return ResourceManager.GetString("AssemblyContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string CaptionColumnHeader {
            get {
                return ResourceManager.GetString("CaptionColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0}_Copy.
        /// </summary>
        internal static string CloneElementName {
            get {
                return ResourceManager.GetString("CloneElementName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want close the window without saving?.
        /// </summary>
        internal static string CloseViewQuestion {
            get {
                return ResourceManager.GetString("CloseViewQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CodeEditorControlCopyButton {
            get {
                return ResourceManager.GetString("CodeEditorControlCopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl+C).
        /// </summary>
        internal static string CodeEditorControlCopyButtonToolTip {
            get {
                return ResourceManager.GetString("CodeEditorControlCopyButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CodeEditorControlCutButton {
            get {
                return ResourceManager.GetString("CodeEditorControlCutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut (Ctrl+X).
        /// </summary>
        internal static string CodeEditorControlCutButtonToolTip {
            get {
                return ResourceManager.GetString("CodeEditorControlCutButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string CodeEditorControlEditButton {
            get {
                return ResourceManager.GetString("CodeEditorControlEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CodeEditorControlFindButton {
            get {
                return ResourceManager.GetString("CodeEditorControlFindButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find and Replace (Ctrl+F).
        /// </summary>
        internal static string CodeEditorControlFindButtonToolTip {
            get {
                return ResourceManager.GetString("CodeEditorControlFindButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CodeEditorControlFormatButton {
            get {
                return ResourceManager.GetString("CodeEditorControlFormatButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Format (Ctrl+Shift+F).
        /// </summary>
        internal static string CodeEditorControlFormatButtonToolTip {
            get {
                return ResourceManager.GetString("CodeEditorControlFormatButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CodeEditorControlPasteButton {
            get {
                return ResourceManager.GetString("CodeEditorControlPasteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste (Ctrl+V).
        /// </summary>
        internal static string CodeEditorControlPasteButtonToolTip {
            get {
                return ResourceManager.GetString("CodeEditorControlPasteButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CodeEditorControlRedoButton {
            get {
                return ResourceManager.GetString("CodeEditorControlRedoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Redo (Ctrl+Y).
        /// </summary>
        internal static string CodeEditorControlRedoButtonToolTip {
            get {
                return ResourceManager.GetString("CodeEditorControlRedoButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        internal static string CodeEditorControlUndoButton {
            get {
                return ResourceManager.GetString("CodeEditorControlUndoButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undo (Ctrl+Z).
        /// </summary>
        internal static string CodeEditorControlUndoButtonToolTip {
            get {
                return ResourceManager.GetString("CodeEditorControlUndoButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ConfigDesignerAddButton {
            get {
                return ResourceManager.GetString("ConfigDesignerAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Document.
        /// </summary>
        internal static string ConfigDesignerAddDocumentButton {
            get {
                return ResourceManager.GetString("ConfigDesignerAddDocumentButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Menu.
        /// </summary>
        internal static string ConfigDesignerAddMenuButton {
            get {
                return ResourceManager.GetString("ConfigDesignerAddMenuButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assemblies.
        /// </summary>
        internal static string ConfigDesignerAssemblies {
            get {
                return ResourceManager.GetString("ConfigDesignerAssemblies", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string ConfigDesignerConfiguration {
            get {
                return ResourceManager.GetString("ConfigDesignerConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ConfigDesignerDeleteButton {
            get {
                return ResourceManager.GetString("ConfigDesignerDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete configuration item &apos;{0}&apos;?.
        /// </summary>
        internal static string ConfigDesignerDeleteQuestion {
            get {
                return ResourceManager.GetString("ConfigDesignerDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string ConfigDesignerDocuments {
            get {
                return ResourceManager.GetString("ConfigDesignerDocuments", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ConfigDesignerEditButton {
            get {
                return ResourceManager.GetString("ConfigDesignerEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchanges.
        /// </summary>
        internal static string ConfigDesignerExchanges {
            get {
                return ResourceManager.GetString("ConfigDesignerExchanges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string ConfigDesignerMenu {
            get {
                return ResourceManager.GetString("ConfigDesignerMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string ConfigDesignerRefreshButton {
            get {
                return ResourceManager.GetString("ConfigDesignerRefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution Explorer.
        /// </summary>
        internal static string ConfigTreeCaption {
            get {
                return ResourceManager.GetString("ConfigTreeCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected item?.
        /// </summary>
        internal static string DeleteActionQuestion {
            get {
                return ResourceManager.GetString("DeleteActionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &apos;{0}&apos;?.
        /// </summary>
        internal static string DeleteConfigElementQuestion {
            get {
                return ResourceManager.GetString("DeleteConfigElementQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete selected item?.
        /// </summary>
        internal static string DeleteItemActionQuestion {
            get {
                return ResourceManager.GetString("DeleteItemActionQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deploy.
        /// </summary>
        internal static string DeployView {
            get {
                return ResourceManager.GetString("DeployView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Designer.
        /// </summary>
        internal static string DesignerView {
            get {
                return ResourceManager.GetString("DesignerView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents.
        /// </summary>
        internal static string DocumentContainer {
            get {
                return ResourceManager.GetString("DocumentContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string DocumentDesignerAddButton {
            get {
                return ResourceManager.GetString("DocumentDesignerAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DocumentDesignerDeleteButton {
            get {
                return ResourceManager.GetString("DocumentDesignerDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete document item &apos;{0}&apos;?.
        /// </summary>
        internal static string DocumentDesignerDeleteQuestion {
            get {
                return ResourceManager.GetString("DocumentDesignerDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string DocumentDesignerEditButton {
            get {
                return ResourceManager.GetString("DocumentDesignerEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string DocumentDesignerRefreshButton {
            get {
                return ResourceManager.GetString("DocumentDesignerRefreshButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string DocumentSchemaDesignerAddButton {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Object and Array can contain properties..
        /// </summary>
        internal static string DocumentSchemaDesignerCannotContainProperties {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerCannotContainProperties", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination item is a subitem of the source item..
        /// </summary>
        internal static string DocumentSchemaDesignerCannotMoveParentToChild {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerCannotMoveParentToChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string DocumentSchemaDesignerCopyButton {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerCopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl+C).
        /// </summary>
        internal static string DocumentSchemaDesignerCopyButtonToolTip {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerCopyButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string DocumentSchemaDesignerCutButton {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerCutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut (Ctrl+X).
        /// </summary>
        internal static string DocumentSchemaDesignerCutButtonToolTip {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerCutButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string DocumentSchemaDesignerDeleteButton {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete property &apos;{0}&apos;?.
        /// </summary>
        internal static string DocumentSchemaDesignerDeleteQuestion {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string DocumentSchemaDesignerEditButton {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string DocumentSchemaDesignerMoveDownButton {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerMoveDownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down (Alt+Down).
        /// </summary>
        internal static string DocumentSchemaDesignerMoveDownButtonToolTip {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerMoveDownButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string DocumentSchemaDesignerMoveUpButton {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerMoveUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up (Alt+Up).
        /// </summary>
        internal static string DocumentSchemaDesignerMoveUpButtonToolTip {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerMoveUpButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string DocumentSchemaDesignerPasteButton {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerPasteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste (Ctrl+V).
        /// </summary>
        internal static string DocumentSchemaDesignerPasteButtonToolTip {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerPasteButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Schema.
        /// </summary>
        internal static string DocumentSchemaDesignerRootText {
            get {
                return ResourceManager.GetString("DocumentSchemaDesignerRootText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Elements.
        /// </summary>
        internal static string EditPanelCaption {
            get {
                return ResourceManager.GetString("EditPanelCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find And Replace.
        /// </summary>
        internal static string FindAndReplaceDialogTitle {
            get {
                return ResourceManager.GetString("FindAndReplaceDialogTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close (Esc).
        /// </summary>
        internal static string FindAndReplaceElementCloseButtonToolTip {
            get {
                return ResourceManager.GetString("FindAndReplaceElementCloseButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next.
        /// </summary>
        internal static string FindAndReplaceElementFindNextButton {
            get {
                return ResourceManager.GetString("FindAndReplaceElementFindNextButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Next (F3).
        /// </summary>
        internal static string FindAndReplaceElementFindNextButtonToolTip {
            get {
                return ResourceManager.GetString("FindAndReplaceElementFindNextButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Previous.
        /// </summary>
        internal static string FindAndReplaceElementFindPreviousButton {
            get {
                return ResourceManager.GetString("FindAndReplaceElementFindPreviousButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find Previous (Shift+F3).
        /// </summary>
        internal static string FindAndReplaceElementFindPreviousButtonToolTip {
            get {
                return ResourceManager.GetString("FindAndReplaceElementFindPreviousButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Find....
        /// </summary>
        internal static string FindAndReplaceElementFindWhat {
            get {
                return ResourceManager.GetString("FindAndReplaceElementFindWhat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Match case.
        /// </summary>
        internal static string FindAndReplaceElementMatchCase {
            get {
                return ResourceManager.GetString("FindAndReplaceElementMatchCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All.
        /// </summary>
        internal static string FindAndReplaceElementReplaceAllButton {
            get {
                return ResourceManager.GetString("FindAndReplaceElementReplaceAllButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace All (Alt+A).
        /// </summary>
        internal static string FindAndReplaceElementReplaceAllButtonToolTip {
            get {
                return ResourceManager.GetString("FindAndReplaceElementReplaceAllButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace.
        /// </summary>
        internal static string FindAndReplaceElementReplaceButton {
            get {
                return ResourceManager.GetString("FindAndReplaceElementReplaceButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace Next (Alt+R).
        /// </summary>
        internal static string FindAndReplaceElementReplaceButtonToolTip {
            get {
                return ResourceManager.GetString("FindAndReplaceElementReplaceButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace....
        /// </summary>
        internal static string FindAndReplaceElementReplaceWith {
            get {
                return ResourceManager.GetString("FindAndReplaceElementReplaceWith", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Whole word.
        /// </summary>
        internal static string FindAndReplaceElementWholeWord {
            get {
                return ResourceManager.GetString("FindAndReplaceElementWholeWord", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generators.
        /// </summary>
        internal static string GeneratorContainer {
            get {
                return ResourceManager.GetString("GeneratorContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot delete columns..
        /// </summary>
        internal static string GridPanelCannotDeleteColumns {
            get {
                return ResourceManager.GetString("GridPanelCannotDeleteColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnSpan cannot be less one..
        /// </summary>
        internal static string GridPanelColumnSpanCannotBeLessOne {
            get {
                return ResourceManager.GetString("GridPanelColumnSpanCannotBeLessOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        internal static string HomePageText {
            get {
                return ResourceManager.GetString("HomePageText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading....
        /// </summary>
        internal static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MenuContainer {
            get {
                return ResourceManager.GetString("MenuContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string MenuDesignerAddButton {
            get {
                return ResourceManager.GetString("MenuDesignerAddButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination item is a subitem of the source item..
        /// </summary>
        internal static string MenuDesignerCannotMoveParentToChild {
            get {
                return ResourceManager.GetString("MenuDesignerCannotMoveParentToChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string MenuDesignerCopyButton {
            get {
                return ResourceManager.GetString("MenuDesignerCopyButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy (Ctrl+C).
        /// </summary>
        internal static string MenuDesignerCopyButtonToolTip {
            get {
                return ResourceManager.GetString("MenuDesignerCopyButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string MenuDesignerCutButton {
            get {
                return ResourceManager.GetString("MenuDesignerCutButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut (Ctrl+X).
        /// </summary>
        internal static string MenuDesignerCutButtonToolTip {
            get {
                return ResourceManager.GetString("MenuDesignerCutButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string MenuDesignerDeleteButton {
            get {
                return ResourceManager.GetString("MenuDesignerDeleteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete menu item &apos;{0}&apos;?.
        /// </summary>
        internal static string MenuDesignerDeleteQuestion {
            get {
                return ResourceManager.GetString("MenuDesignerDeleteQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string MenuDesignerEditButton {
            get {
                return ResourceManager.GetString("MenuDesignerEditButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string MenuDesignerMoveDownButton {
            get {
                return ResourceManager.GetString("MenuDesignerMoveDownButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down (Alt+Down).
        /// </summary>
        internal static string MenuDesignerMoveDownButtonToolTip {
            get {
                return ResourceManager.GetString("MenuDesignerMoveDownButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string MenuDesignerMoveUpButton {
            get {
                return ResourceManager.GetString("MenuDesignerMoveUpButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up (Alt+Up).
        /// </summary>
        internal static string MenuDesignerMoveUpButtonToolTip {
            get {
                return ResourceManager.GetString("MenuDesignerMoveUpButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string MenuDesignerPasteButton {
            get {
                return ResourceManager.GetString("MenuDesignerPasteButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste (Ctrl+V).
        /// </summary>
        internal static string MenuDesignerPasteButtonToolTip {
            get {
                return ResourceManager.GetString("MenuDesignerPasteButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MenuDesignerRootItemText {
            get {
                return ResourceManager.GetString("MenuDesignerRootItemText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assembly.
        /// </summary>
        internal static string MetadataTypeAssembly {
            get {
                return ResourceManager.GetString("MetadataTypeAssembly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration.
        /// </summary>
        internal static string MetadataTypeConfiguration {
            get {
                return ResourceManager.GetString("MetadataTypeConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document.
        /// </summary>
        internal static string MetadataTypeDocument {
            get {
                return ResourceManager.GetString("MetadataTypeDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator.
        /// </summary>
        internal static string MetadataTypeGenerator {
            get {
                return ResourceManager.GetString("MetadataTypeGenerator", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string MetadataTypeIsNotSupported {
            get {
                return ResourceManager.GetString("MetadataTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Menu.
        /// </summary>
        internal static string MetadataTypeMenu {
            get {
                return ResourceManager.GetString("MetadataTypeMenu", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintView.
        /// </summary>
        internal static string MetadataTypePrintView {
            get {
                return ResourceManager.GetString("MetadataTypePrintView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Process.
        /// </summary>
        internal static string MetadataTypeProcess {
            get {
                return ResourceManager.GetString("MetadataTypeProcess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        internal static string MetadataTypeRegister {
            get {
                return ResourceManager.GetString("MetadataTypeRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report.
        /// </summary>
        internal static string MetadataTypeReport {
            get {
                return ResourceManager.GetString("MetadataTypeReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenario.
        /// </summary>
        internal static string MetadataTypeScenario {
            get {
                return ResourceManager.GetString("MetadataTypeScenario", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service.
        /// </summary>
        internal static string MetadataTypeService {
            get {
                return ResourceManager.GetString("MetadataTypeService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string MetadataTypeStatus {
            get {
                return ResourceManager.GetString("MetadataTypeStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidationError.
        /// </summary>
        internal static string MetadataTypeValidationError {
            get {
                return ResourceManager.GetString("MetadataTypeValidationError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidationWarning.
        /// </summary>
        internal static string MetadataTypeValidationWarning {
            get {
                return ResourceManager.GetString("MetadataTypeValidationWarning", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View.
        /// </summary>
        internal static string MetadataTypeView {
            get {
                return ResourceManager.GetString("MetadataTypeView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata.
        /// </summary>
        internal static string MetadataView {
            get {
                return ResourceManager.GetString("MetadataView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Migration.
        /// </summary>
        internal static string MigrationView {
            get {
                return ResourceManager.GetString("MigrationView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameColumnHeader {
            get {
                return ResourceManager.GetString("NameColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintViews.
        /// </summary>
        internal static string PrintViewContainer {
            get {
                return ResourceManager.GetString("PrintViewContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processes.
        /// </summary>
        internal static string ProcessContainer {
            get {
                return ResourceManager.GetString("ProcessContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Editor.
        /// </summary>
        internal static string PropertyEditorControlCaption {
            get {
                return ResourceManager.GetString("PropertyEditorControlCaption", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete &apos;{0}&apos;?.
        /// </summary>
        internal static string PropertyEditorControlDeletePropertyQuestion {
            get {
                return ResourceManager.GetString("PropertyEditorControlDeletePropertyQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reconnect.
        /// </summary>
        internal static string Reconnect {
            get {
                return ResourceManager.GetString("Reconnect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        internal static string Refresh {
            get {
                return ResourceManager.GetString("Refresh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Registers.
        /// </summary>
        internal static string RegisterContainer {
            get {
                return ResourceManager.GetString("RegisterContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reports.
        /// </summary>
        internal static string ReportContainer {
            get {
                return ResourceManager.GetString("ReportContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Designer.
        /// </summary>
        internal static string ReportDesigner {
            get {
                return ResourceManager.GetString("ReportDesigner", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please correct the errors to save..
        /// </summary>
        internal static string SaveValidateViewError {
            get {
                return ResourceManager.GetString("SaveValidateViewError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scenarios.
        /// </summary>
        internal static string ScenarioContainer {
            get {
                return ResourceManager.GetString("ScenarioContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Services.
        /// </summary>
        internal static string ServiceContainer {
            get {
                return ResourceManager.GetString("ServiceContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should specify the event..
        /// </summary>
        internal static string ShouldSpecifyEvent {
            get {
                return ResourceManager.GetString("ShouldSpecifyEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Should specify event handler..
        /// </summary>
        internal static string ShouldSpecifyEventHandler {
            get {
                return ResourceManager.GetString("ShouldSpecifyEventHandler", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source &apos;{0}&apos; has no event &apos;{1}&apos;..
        /// </summary>
        internal static string SourceHasNoEvent {
            get {
                return ResourceManager.GetString("SourceHasNoEvent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statuses.
        /// </summary>
        internal static string StatusContainer {
            get {
                return ResourceManager.GetString("StatusContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OFF.
        /// </summary>
        internal static string ToggleButtonControlTextOff {
            get {
                return ResourceManager.GetString("ToggleButtonControlTextOff", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ON.
        /// </summary>
        internal static string ToggleButtonControlTextOn {
            get {
                return ResourceManager.GetString("ToggleButtonControlTextOn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidationErrors.
        /// </summary>
        internal static string ValidationErrorContainer {
            get {
                return ResourceManager.GetString("ValidationErrorContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ValidationWarnings.
        /// </summary>
        internal static string ValidationWarningContainer {
            get {
                return ResourceManager.GetString("ValidationWarningContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views.
        /// </summary>
        internal static string ViewContainer {
            get {
                return ResourceManager.GetString("ViewContainer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        internal static string ViewPropertyEditorControlAddButtonToolTip {
            get {
                return ResourceManager.GetString("ViewPropertyEditorControlAddButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string ViewPropertyEditorControlDeleteButtonToolTip {
            get {
                return ResourceManager.GetString("ViewPropertyEditorControlDeleteButtonToolTip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        internal static string ViewPropertyEditorControlEditButtonToolTip {
            get {
                return ResourceManager.GetString("ViewPropertyEditorControlEditButtonToolTip", resourceCulture);
            }
        }
    }
}
