//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.Api.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.Api.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; access denied to configuration &quot;{1}&quot;, document &quot;{2}&quot;, action &quot;{3}&quot;. .
        /// </summary>
        public static string AccessDeniedToAction {
            get {
                return ResourceManager.GetString("AccessDeniedToAction", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; access denied to configuration &quot;{1}&quot;..
        /// </summary>
        public static string AccessDeniedToConfiguration {
            get {
                return ResourceManager.GetString("AccessDeniedToConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; access denied to configuration &quot;{1}&quot;, document &quot;{2}&quot;..
        /// </summary>
        public static string AccessDeniedToDocument {
            get {
                return ResourceManager.GetString("AccessDeniedToDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; access denied to configuration &quot;{1}&quot;, document &quot;{2}&quot;, action &quot;{3}&quot;, record with identifier &quot;{4}&quot;.
        /// </summary>
        public static string AccessDeniedToDocumentInstance {
            get {
                return ResourceManager.GetString("AccessDeniedToDocumentInstance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action &apos;{0}&apos; failed with exception: {1}.
        /// </summary>
        public static string ActionFailedWithException {
            get {
                return ResourceManager.GetString("ActionFailedWithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action unit should not be empty..
        /// </summary>
        public static string ActionUnitShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("ActionUnitShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ambiguous service definition!.
        /// </summary>
        public static string AmbiguousServiceDefinitionError {
            get {
                return ResourceManager.GetString("AmbiguousServiceDefinitionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Application with name {0} and version {1} not found. .
        /// </summary>
        public static string ApplicationNotFound {
            get {
                return ResourceManager.GetString("ApplicationNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Attempt attach to test server: {0}..
        /// </summary>
        public static string AttemptAttachToTestServer {
            get {
                return ResourceManager.GetString("AttemptAttachToTestServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Authorization action should not be empty..
        /// </summary>
        public static string AuthorizationPointShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("AuthorizationPointShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Binary content max size {0} is exceed..
        /// </summary>
        public static string BinaryContentMaxSizeIsExceed {
            get {
                return ResourceManager.GetString("BinaryContentMaxSizeIsExceed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Batch completed successfully.
        /// </summary>
        public static string BatchCompletedSuccessfully {
            get {
                return ResourceManager.GetString("BatchCompletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Business logic error..
        /// </summary>
        public static string BusinessLogicError {
            get {
                return ResourceManager.GetString("BusinessLogicError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot attach to test server..
        /// </summary>
        public static string CannotAttachToTestServer {
            get {
                return ResourceManager.GetString("CannotAttachToTestServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot deserialize type &apos;{0}&apos;..
        /// </summary>
        public static string CannotDeserializeTypeError {
            get {
                return ResourceManager.GetString("CannotDeserializeTypeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add unsaved user to role.
        /// </summary>
        public static string CantAddUnsavedUserToRole {
            get {
                return ResourceManager.GetString("CantAddUnsavedUserToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t get specific configuration without specification of configuration version.
        /// </summary>
        public static string CantGetSpecificConfigurationWithoutVersion {
            get {
                return ResourceManager.GetString("CantGetSpecificConfigurationWithoutVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t parse IQL query.
        /// </summary>
        public static string CantParseIQLQuery {
            get {
                return ResourceManager.GetString("CantParseIQLQuery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove item from parent.
        /// </summary>
        public static string CantRemoveItemFromParent {
            get {
                return ResourceManager.GetString("CantRemoveItemFromParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove unsaved user from role..
        /// </summary>
        public static string CantRemoveUnsavedUserFromRole {
            get {
                return ResourceManager.GetString("CantRemoveUnsavedUserFromRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove user from role admin or no one user will be admin..
        /// </summary>
        public static string CantRemoveUserFromAdminRole {
            get {
                return ResourceManager.GetString("CantRemoveUserFromAdminRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim removed successfully.
        /// </summary>
        public static string ClaimRemovedSuccessfully {
            get {
                return ResourceManager.GetString("ClaimRemovedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Clipboard is empty..
        /// </summary>
        public static string ClipboardIsEmpty {
            get {
                return ResourceManager.GetString("ClipboardIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collection cannot be modified..
        /// </summary>
        public static string CollectionCanNotBeModified {
            get {
                return ResourceManager.GetString("CollectionCanNotBeModified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complex authorization action should not be empty..
        /// </summary>
        public static string ComplexAuthorizationShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("ComplexAuthorizationShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration and UserName should not be empty on grant access..
        /// </summary>
        public static string ConfigurationAndUserNameShouldNotBeEmptyForGrantAccess {
            get {
                return ResourceManager.GetString("ConfigurationAndUserNameShouldNotBeEmptyForGrantAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration id should not be empty..
        /// </summary>
        public static string ConfigurationIdShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("ConfigurationIdShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration name not specified!.
        /// </summary>
        public static string ConfigurationNameNotSpecified {
            get {
                return ResourceManager.GetString("ConfigurationNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration &quot;{0}&quot; referenced in &quot;{1}&quot; not found..
        /// </summary>
        public static string ConfigurationReferencedInObjectNotFound {
            get {
                return ResourceManager.GetString("ConfigurationReferencedInObjectNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete element {0}? .
        /// </summary>
        public static string ConfirmDeleteDocument {
            get {
                return ResourceManager.GetString("ConfirmDeleteDocument", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Credentials action should not be empty.
        /// </summary>
        public static string CredentialsActionShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("CredentialsActionShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete action should not be empty..
        /// </summary>
        public static string DeleteActionShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("DeleteActionShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted documents identifiers list must be not null..
        /// </summary>
        public static string DeletedDocumentsIdentifiersShouldNotBeNull {
            get {
                return ResourceManager.GetString("DeletedDocumentsIdentifiersShouldNotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document attached successfully..
        /// </summary>
        public static string DocumentAttachedSuccessfully {
            get {
                return ResourceManager.GetString("DocumentAttachedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document content successfully uploaded.
        /// </summary>
        public static string DocumentContentSuccessfullyUploaded {
            get {
                return ResourceManager.GetString("DocumentContentSuccessfullyUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document with identifier &quot;{0}&quot; deleted successfully.
        /// </summary>
        public static string DocumentDeletedSuccessfully {
            get {
                return ResourceManager.GetString("DocumentDeletedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document filter events context.
        /// </summary>
        public static string DocumentFilterEventContext {
            get {
                return ResourceManager.GetString("DocumentFilterEventContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document identifier should not be empty..
        /// </summary>
        public static string DocumentIdShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("DocumentIdShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document metadata with name &quot;{0}&quot; not found..
        /// </summary>
        public static string DocumentMetadataNotFound {
            get {
                return ResourceManager.GetString("DocumentMetadataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document move context.
        /// </summary>
        public static string DocumentMoveContextType {
            get {
                return ResourceManager.GetString("DocumentMoveContextType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document move result context.
        /// </summary>
        public static string DocumentMoveResultContext {
            get {
                return ResourceManager.GetString("DocumentMoveResultContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document with identifier &quot;{0}&quot; not found..
        /// </summary>
        public static string DocumentNotFound {
            get {
                return ResourceManager.GetString("DocumentNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document provider for type &quot;{0}&quot; not found..
        /// </summary>
        public static string DocumentProviderTypeNotFound {
            get {
                return ResourceManager.GetString("DocumentProviderTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document search context.
        /// </summary>
        public static string DocumentSearchContext {
            get {
                return ResourceManager.GetString("DocumentSearchContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not allowed to set relevant version to user {0}..
        /// </summary>
        public static string DoesNotAllowedToSetVersion {
            get {
                return ResourceManager.GetString("DoesNotAllowedToSetVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Access to configuration object by identifier denied.
        /// </summary>
        public static string ErrorAccessDeniedByIdentifier {
            get {
                return ResourceManager.GetString("ErrorAccessDeniedByIdentifier", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration name is empty.
        /// </summary>
        public static string ErrorConfigNameIsEmpty {
            get {
                return ResourceManager.GetString("ErrorConfigNameIsEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View metadata {0} has another metadata type. Metadata type: {1}, query metadata type: {2}..
        /// </summary>
        public static string ErrorIncorrectViewMetadataType {
            get {
                return ResourceManager.GetString("ErrorIncorrectViewMetadataType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Undefined configuration metadata container type.
        /// </summary>
        public static string ErrorMetadataContainerUndefined {
            get {
                return ResourceManager.GetString("ErrorMetadataContainerUndefined", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata manager for specified type not found..
        /// </summary>
        public static string ErrorMetadataManagerForTypeNotFound {
            get {
                return ResourceManager.GetString("ErrorMetadataManagerForTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in parsing JSON configuration.
        /// </summary>
        public static string ErrorParsingJsonConfiguration {
            get {
                return ResourceManager.GetString("ErrorParsingJsonConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Errors validation failed with exception: {0}.
        /// </summary>
        public static string ErrorsValidationFailedWithException {
            get {
                return ResourceManager.GetString("ErrorsValidationFailedWithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Executable file not found..
        /// </summary>
        public static string ExecutableFileNotFound {
            get {
                return ResourceManager.GetString("ExecutableFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail action should not be empty..
        /// </summary>
        public static string FailActionShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("FailActionShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t create request local without controller factory.
        /// </summary>
        public static string FailCreateRequestLocal {
            get {
                return ResourceManager.GetString("FailCreateRequestLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to grant access role: {0}.
        /// </summary>
        public static string FailToApplyAccessRole {
            get {
                return ResourceManager.GetString("FailToApplyAccessRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to get irrelevant versions for user: &quot;{0}&quot;.
        /// </summary>
        public static string FailToGetIrrelevantVersions {
            get {
                return ResourceManager.GetString("FailToGetIrrelevantVersions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to remove.
        /// </summary>
        public static string FailToRemoveParent {
            get {
                return ResourceManager.GetString("FailToRemoveParent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to set user access: {0}.
        /// </summary>
        public static string FailToSetUserAccess {
            get {
                return ResourceManager.GetString("FailToSetUserAccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File attached successfully..
        /// </summary>
        public static string FileAttachedSuccessfully {
            get {
                return ResourceManager.GetString("FileAttachedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to File upload context.
        /// </summary>
        public static string FileUploadContext {
            get {
                return ResourceManager.GetString("FileUploadContext", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator metadata can&apos;t be replaced, should be inserted or deleted only..
        /// </summary>
        public static string GeneratorMetadataCantBeReplaced {
            get {
                return ResourceManager.GetString("GeneratorMetadataCantBeReplaced", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator metadata change collection item index not supported while..
        /// </summary>
        public static string GeneratorMetadataChangeCollectionItemIndexNotSupported {
            get {
                return ResourceManager.GetString("GeneratorMetadataChangeCollectionItemIndexNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator metadata not support partial metadata changes..
        /// </summary>
        public static string GeneratorMetadataPartialChangesNotSupported {
            get {
                return ResourceManager.GetString("GeneratorMetadataPartialChangesNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator name should not be empty..
        /// </summary>
        public static string GeneratorNameShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("GeneratorNameShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fail to index item: object has incorrect and inappropriate structure for current index type mapping..
        /// </summary>
        public static string InappropriateItemMapping {
            get {
                return ResourceManager.GetString("InappropriateItemMapping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration name should be on the latin and can&apos;t include special characters.
        /// </summary>
        public static string IncorrectConfigurationName {
            get {
                return ResourceManager.GetString("IncorrectConfigurationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect file download request..
        /// </summary>
        public static string IncorrectDownloadRequest {
            get {
                return ResourceManager.GetString("IncorrectDownloadRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to index name should not be empty..
        /// </summary>
        public static string IndexNameShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("IndexNameShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Экземпляр не является типом объекта (например, массив).
        /// </summary>
        public static string InstanceIsNotAnObject {
            get {
                return ResourceManager.GetString("InstanceIsNotAnObject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Instance not found to attach file. InstanceId: {0}.
        /// </summary>
        public static string InstanceNotFoundToAttachFile {
            get {
                return ResourceManager.GetString("InstanceNotFoundToAttachFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Internal server error..
        /// </summary>
        public static string InternalServerError {
            get {
                return ResourceManager.GetString("InternalServerError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to document &quot;{0}&quot; deleted.
        /// </summary>
        public static string LogDocumentDeleted {
            get {
                return ResourceManager.GetString("LogDocumentDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Member &apos;{0}&apos; was not found or cannot be invoked..
        /// </summary>
        public static string MemberWasNotFoundOrCannotBeInvoked {
            get {
                return ResourceManager.GetString("MemberWasNotFoundOrCannotBeInvoked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata container for specified metadata type not found..
        /// </summary>
        public static string MetadataContainerForSpecifiedTypeNotFound {
            get {
                return ResourceManager.GetString("MetadataContainerForSpecifiedTypeNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata element with identifier {0} and version {1} not found..
        /// </summary>
        public static string MetadataElementNotFound {
            get {
                return ResourceManager.GetString("MetadataElementNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata id should not be empty..
        /// </summary>
        public static string MetadataIdShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("MetadataIdShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata name not specified..
        /// </summary>
        public static string MetadataNameNotSpecified {
            get {
                return ResourceManager.GetString("MetadataNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata type for generator should not be empty..
        /// </summary>
        public static string MetadataTypeForGeneratorShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("MetadataTypeForGeneratorShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name is already added..
        /// </summary>
        public static string NameIsAlreadyAdded {
            get {
                return ResourceManager.GetString("NameIsAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need confirm.
        /// </summary>
        public static string NeedConfirm {
            get {
                return ResourceManager.GetString("NeedConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need select inspected item.
        /// </summary>
        public static string NeedToSelectItem {
            get {
                return ResourceManager.GetString("NeedToSelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No item selected..
        /// </summary>
        public static string NoItemSelected {
            get {
                return ResourceManager.GetString("NoItemSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all request parameters are filed..
        /// </summary>
        public static string NotAllRequestParamsAreFiled {
            get {
                return ResourceManager.GetString("NotAllRequestParamsAreFiled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not all request params are specified..
        /// </summary>
        public static string NotAllRequestParamsAreSpecified {
            get {
                return ResourceManager.GetString("NotAllRequestParamsAreSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Property path cannot be null or empty..
        /// </summary>
        public static string PropertyPathCannotBeNullOrEmpty {
            get {
                return ResourceManager.GetString("PropertyPathCannotBeNullOrEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {0} property of {1} should&apos;nt be empty..
        /// </summary>
        public static string PropertyShouldntBeEmpty {
            get {
                return ResourceManager.GetString("PropertyShouldntBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to query provider for specified metadata not found. .
        /// </summary>
        public static string QueryMetadataProviderNotFound {
            get {
                return ResourceManager.GetString("QueryMetadataProviderNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register action should not be empty..
        /// </summary>
        public static string RegisterActionShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("RegisterActionShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Remote server not found..
        /// </summary>
        public static string RemoteServerNotFound {
            get {
                return ResourceManager.GetString("RemoteServerNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Schema does not contain &apos;id&apos; property: &apos;{0}&apos;..
        /// </summary>
        public static string SchemaDoesNotContainIdProperty {
            get {
                return ResourceManager.GetString("SchemaDoesNotContainIdProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Schema is incorrect or not declared: &apos;{0}&apos;..
        /// </summary>
        public static string SchemaIncorrectOrNotDeclared {
            get {
                return ResourceManager.GetString("SchemaIncorrectOrNotDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Schema &apos;{0}&apos; is already declared: &apos;{1}&apos;..
        /// </summary>
        public static string SchemaIsAlreadyDeclared {
            get {
                return ResourceManager.GetString("SchemaIsAlreadyDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Path &apos;{0}&apos;..
        /// </summary>
        public static string SchemaPathInfo {
            get {
                return ResourceManager.GetString("SchemaPathInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server errors validation failed with exception: {0}.
        /// </summary>
        public static string ServerErrorsValidationFailedWithException {
            get {
                return ResourceManager.GetString("ServerErrorsValidationFailedWithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server warnings validation failed with exception: {0}.
        /// </summary>
        public static string ServerWarningsValidationFailedWithException {
            get {
                return ResourceManager.GetString("ServerWarningsValidationFailedWithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not registered! Please check type of request (GET,POST) and name of invoked service instance..
        /// </summary>
        public static string ServiceNotFoundError {
            get {
                return ResourceManager.GetString("ServiceNotFoundError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service not registered..
        /// </summary>
        public static string ServiceNotRegistered {
            get {
                return ResourceManager.GetString("ServiceNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Session created successfully.
        /// </summary>
        public static string SessionCreatedSuccessfully {
            get {
                return ResourceManager.GetString("SessionCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SessionId and Document should&apos;nt be empty..
        /// </summary>
        public static string SessionIdAndDocumentShouldntBeEmpty {
            get {
                return ResourceManager.GetString("SessionIdAndDocumentShouldntBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution assemblies successfully updated..
        /// </summary>
        public static string SolutionAssembliesSuccessfullyUploaded {
            get {
                return ResourceManager.GetString("SolutionAssembliesSuccessfullyUploaded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Solution with name &quot;{0}&quot; and version &quot;{1} not found&quot;..
        /// </summary>
        public static string SolutionNotFound {
            get {
                return ResourceManager.GetString("SolutionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State updater should not be empty..
        /// </summary>
        public static string StateUpdaterShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("StateUpdaterShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to State validator should not be empty..
        /// </summary>
        public static string StateValidatorShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("StateValidatorShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sucess action should not be empty..
        /// </summary>
        public static string SuccessActionShouldNotBeEmpty {
            get {
                return ResourceManager.GetString("SuccessActionShouldNotBeEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Target object cannot be null..
        /// </summary>
        public static string TargetObjectCannotBeNull {
            get {
                return ResourceManager.GetString("TargetObjectCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type is already added..
        /// </summary>
        public static string TypeIsAlreadyAdded {
            get {
                return ResourceManager.GetString("TypeIsAlreadyAdded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type should have default constructor..
        /// </summary>
        public static string TypeShouldHaveDefaultConstructor {
            get {
                return ResourceManager.GetString("TypeShouldHaveDefaultConstructor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Type should not be abstract..
        /// </summary>
        public static string TypeShouldNotBeAbstract {
            get {
                return ResourceManager.GetString("TypeShouldNotBeAbstract", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to find user with user name: {0}.
        /// </summary>
        public static string UnableToFindUser {
            get {
                return ResourceManager.GetString("UnableToFindUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unknown.
        /// </summary>
        public static string UnknownRouteSection {
            get {
                return ResourceManager.GetString("UnknownRouteSection", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UnsatifiedAppVersion.
        /// </summary>
        public static string UnsatisfiedVersionNumber {
            get {
                return ResourceManager.GetString("UnsatisfiedVersionNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Url encoded data processing completed..
        /// </summary>
        public static string UrlEncodedDataProcessingComplete {
            get {
                return ResourceManager.GetString("UrlEncodedDataProcessingComplete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User created successfully.
        /// </summary>
        public static string UserCreatedSuccessfully {
            get {
                return ResourceManager.GetString("UserCreatedSuccessfully", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User with Id &apos;{0}&apos; not found in persistent storage.
        /// </summary>
        public static string UserNotFound {
            get {
                return ResourceManager.GetString("UserNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User &quot;{0}&quot; not found..
        /// </summary>
        public static string UserToRemoveClaimNotFound {
            get {
                return ResourceManager.GetString("UserToRemoveClaimNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validator not found..
        /// </summary>
        public static string ValidatorNotFound {
            get {
                return ResourceManager.GetString("ValidatorNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value is not a list of identifiers.
        /// </summary>
        public static string ValueIsNotIdentifiersList {
            get {
                return ResourceManager.GetString("ValueIsNotIdentifiersList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warning.
        /// </summary>
        public static string Warnings {
            get {
                return ResourceManager.GetString("Warnings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Warnings validation failed with exception: {0}.
        /// </summary>
        public static string WarningsValidationFailedWithException {
            get {
                return ResourceManager.GetString("WarningsValidationFailedWithException", resourceCulture);
            }
        }
    }
}
