//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.Core.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.Core.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Could not get status for the subsystem..
        /// </summary>
        public static string CouldNotGetStatusForTheSubsystem {
            get {
                return ResourceManager.GetString("CouldNotGetStatusForTheSubsystem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need confirm.
        /// </summary>
        public static string NeedConfirm {
            get {
                return ResourceManager.GetString("NeedConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Schema does not contain &apos;id&apos; property: &apos;{0}&apos;..
        /// </summary>
        public static string SchemaDoesNotContainIdProperty {
            get {
                return ResourceManager.GetString("SchemaDoesNotContainIdProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Schema is incorrect or not declared: &apos;{0}&apos;..
        /// </summary>
        public static string SchemaIncorrectOrNotDeclared {
            get {
                return ResourceManager.GetString("SchemaIncorrectOrNotDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to JSON Schema &apos;{0}&apos; is already declared: &apos;{1}&apos;..
        /// </summary>
        public static string SchemaIsAlreadyDeclared {
            get {
                return ResourceManager.GetString("SchemaIsAlreadyDeclared", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  Path &apos;{0}&apos;..
        /// </summary>
        public static string SchemaPathInfo {
            get {
                return ResourceManager.GetString("SchemaPathInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Validator not found..
        /// </summary>
        public static string ValidatorNotFound {
            get {
                return ResourceManager.GetString("ValidatorNotFound", resourceCulture);
            }
        }
    }
}
