//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.Core.Properties {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.Core.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not create IoC container module..
        /// </summary>
        internal static string CannotCreateContainerModule {
            get {
                return ResourceManager.GetString("CannotCreateContainerModule", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot initialize service correctly..
        /// </summary>
        internal static string CannotInitializeServiceCorrectly {
            get {
                return ResourceManager.GetString("CannotInitializeServiceCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start service correctly..
        /// </summary>
        internal static string CannotStartServiceCorrectly {
            get {
                return ResourceManager.GetString("CannotStartServiceCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot stop service correctly..
        /// </summary>
        internal static string CannotStopServiceCorrectly {
            get {
                return ResourceManager.GetString("CannotStopServiceCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request processing completed with unexpected exception..
        /// </summary>
        internal static string RequestProcessingCompletedWithUnexpectedException {
            get {
                return ResourceManager.GetString("RequestProcessingCompletedWithUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name cannot be null or whitespace..
        /// </summary>
        internal static string ServerNameCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ServerNameCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name &apos;{0}&apos; is not local address..
        /// </summary>
        internal static string ServerNameIsNotLocal {
            get {
                return ResourceManager.GetString("ServerNameIsNotLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server port &apos;{0}&apos; is incorrect. Server port should be more than zero..
        /// </summary>
        internal static string ServerPortIsIncorrect {
            get {
                return ResourceManager.GetString("ServerPortIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server scheme cannot be null or whitespace..
        /// </summary>
        internal static string ServerSchemeCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ServerSchemeCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server scheme &apos;{0}&apos; is not supported. Use &apos;http&apos; or &apos;https&apos;..
        /// </summary>
        internal static string ServerSchemeIsNotSupported {
            get {
                return ResourceManager.GetString("ServerSchemeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service host has been successfully started..
        /// </summary>
        internal static string ServiceHostHasBeenSuccessfullyStarted {
            get {
                return ResourceManager.GetString("ServiceHostHasBeenSuccessfullyStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service host has been successfully stopped..
        /// </summary>
        internal static string ServiceHostHasBeenSuccessfullyStopped {
            get {
                return ResourceManager.GetString("ServiceHostHasBeenSuccessfullyStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service host has not been started..
        /// </summary>
        internal static string ServiceHostHasNotBeenStarted {
            get {
                return ResourceManager.GetString("ServiceHostHasNotBeenStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service host has not been stopped..
        /// </summary>
        internal static string ServiceHostHasNotBeenStopped {
            get {
                return ResourceManager.GetString("ServiceHostHasNotBeenStopped", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service host initialization completed with an exception..
        /// </summary>
        internal static string ServiceHostInitializationCompletedWithAnException {
            get {
                return ResourceManager.GetString("ServiceHostInitializationCompletedWithAnException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service host initialization successfully completed..
        /// </summary>
        internal static string ServiceHostInitializationSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("ServiceHostInitializationSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service host initialization was started..
        /// </summary>
        internal static string ServiceHostInitializationWasStarted {
            get {
                return ResourceManager.GetString("ServiceHostInitializationWasStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service host is starting..
        /// </summary>
        internal static string ServiceHostIsStarting {
            get {
                return ResourceManager.GetString("ServiceHostIsStarting", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service host is stopping..
        /// </summary>
        internal static string ServiceHostIsStopping {
            get {
                return ResourceManager.GetString("ServiceHostIsStopping", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving static content..
        /// </summary>
        internal static string ServingStaticContent {
            get {
                return ResourceManager.GetString("ServingStaticContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subsystem is not responding..
        /// </summary>
        internal static string SubsystemIsNotResponding {
            get {
                return ResourceManager.GetString("SubsystemIsNotResponding", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception..
        /// </summary>
        internal static string UnhandledExceptionOwinMiddleware {
            get {
                return ResourceManager.GetString("UnhandledExceptionOwinMiddleware", resourceCulture);
            }
        }
    }
}
