//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.PrintViewDesigner.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.PrintViewDesigner.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OK.
        /// </summary>
        internal static string AcceptButton {
            get {
                return ResourceManager.GetString("AcceptButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Appearance.
        /// </summary>
        internal static string AppearanceCategory {
            get {
                return ResourceManager.GetString("AppearanceCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Background.
        /// </summary>
        internal static string BackgroundProperty {
            get {
                return ResourceManager.GetString("BackgroundProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Barcode.
        /// </summary>
        internal static string BarcodeCategory {
            get {
                return ResourceManager.GetString("BarcodeCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarcodeEan13.
        /// </summary>
        internal static string BarcodeEan13 {
            get {
                return ResourceManager.GetString("BarcodeEan13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CalcCheckSum.
        /// </summary>
        internal static string BarcodeEan13CalcCheckSumProperty {
            get {
                return ResourceManager.GetString("BarcodeEan13CalcCheckSumProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        internal static string BarcodeEan13RotationProperty {
            get {
                return ResourceManager.GetString("BarcodeEan13RotationProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to WideBarRatio.
        /// </summary>
        internal static string BarcodeEan13WideBarRatioProperty {
            get {
                return ResourceManager.GetString("BarcodeEan13WideBarRatioProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BarcodeQr.
        /// </summary>
        internal static string BarcodeQr {
            get {
                return ResourceManager.GetString("BarcodeQr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ErrorCorrection.
        /// </summary>
        internal static string BarcodeQrErrorCorrectionProperty {
            get {
                return ResourceManager.GetString("BarcodeQrErrorCorrectionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        internal static string BarcodeQrRotationProperty {
            get {
                return ResourceManager.GetString("BarcodeQrRotationProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string Bold {
            get {
                return ResourceManager.GetString("Bold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean, &apos;{0}&apos;, &apos;{1}&apos;.
        /// </summary>
        internal static string BooleanFormat {
            get {
                return ResourceManager.GetString("BooleanFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to False value text:.
        /// </summary>
        internal static string BooleanFormatFalseText {
            get {
                return ResourceManager.GetString("BooleanFormatFalseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Boolean.
        /// </summary>
        internal static string BooleanFormatTabHeader {
            get {
                return ResourceManager.GetString("BooleanFormatTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to True value text:.
        /// </summary>
        internal static string BooleanFormatTrueText {
            get {
                return ResourceManager.GetString("BooleanFormatTrueText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Color.
        /// </summary>
        internal static string BorderColorProperty {
            get {
                return ResourceManager.GetString("BorderColorProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Border.
        /// </summary>
        internal static string BorderProperty {
            get {
                return ResourceManager.GetString("BorderProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thickness.
        /// </summary>
        internal static string BorderThicknessProperty {
            get {
                return ResourceManager.GetString("BorderThicknessProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel.
        /// </summary>
        internal static string CancelButton {
            get {
                return ResourceManager.GetString("CancelButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The element cannot be pasted into itself..
        /// </summary>
        internal static string CannotBePastedIntoItself {
            get {
                return ResourceManager.GetString("CannotBePastedIntoItself", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Does not allowed to insert &apos;{0}&apos; into &apos;{1}&apos;..
        /// </summary>
        internal static string CannotInsertChildElement {
            get {
                return ResourceManager.GetString("CannotInsertChildElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The destination element &apos;{0}&apos; is a subitem of the source element &apos;{1}&apos;..
        /// </summary>
        internal static string CannotInsertParentIntoChild {
            get {
                return ResourceManager.GetString("CannotInsertParentIntoChild", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Caption.
        /// </summary>
        internal static string CaptionProperty {
            get {
                return ResourceManager.GetString("CaptionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Collapse All.
        /// </summary>
        internal static string CollapseAll {
            get {
                return ResourceManager.GetString("CollapseAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string ColumnSizeProperty {
            get {
                return ResourceManager.GetString("ColumnSizeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SizeUnit.
        /// </summary>
        internal static string ColumnSizeUnitProperty {
            get {
                return ResourceManager.GetString("ColumnSizeUnitProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common.
        /// </summary>
        internal static string CommonCategory {
            get {
                return ResourceManager.GetString("CommonCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Copy.
        /// </summary>
        internal static string Copy {
            get {
                return ResourceManager.GetString("Copy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cut.
        /// </summary>
        internal static string Cut {
            get {
                return ResourceManager.GetString("Cut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string DataCategory {
            get {
                return ResourceManager.GetString("DataCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime, &apos;{0}&apos;.
        /// </summary>
        internal static string DateTimeFormat {
            get {
                return ResourceManager.GetString("DateTimeFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        internal static string DateTimeFormatSample {
            get {
                return ResourceManager.GetString("DateTimeFormatSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DateTime.
        /// </summary>
        internal static string DateTimeFormatTabHeader {
            get {
                return ResourceManager.GetString("DateTimeFormatTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        internal static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete element &apos;{0}&apos;?.
        /// </summary>
        internal static string DeleteElementQuestion {
            get {
                return ResourceManager.GetString("DeleteElementQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        internal static string DescriptionProperty {
            get {
                return ResourceManager.GetString("DescriptionProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expand All.
        /// </summary>
        internal static string ExpandAll {
            get {
                return ResourceManager.GetString("ExpandAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Export to File.
        /// </summary>
        internal static string Export {
            get {
                return ResourceManager.GetString("Export", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Family.
        /// </summary>
        internal static string FontFamilyProperty {
            get {
                return ResourceManager.GetString("FontFamilyProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Font.
        /// </summary>
        internal static string FontProperty {
            get {
                return ResourceManager.GetString("FontProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string FontSizeProperty {
            get {
                return ResourceManager.GetString("FontSizeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SizeUnit.
        /// </summary>
        internal static string FontSizeUnitProperty {
            get {
                return ResourceManager.GetString("FontSizeUnitProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Condensed.
        /// </summary>
        internal static string FontStretchCondensed {
            get {
                return ResourceManager.GetString("FontStretchCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expanded.
        /// </summary>
        internal static string FontStretchExpanded {
            get {
                return ResourceManager.GetString("FontStretchExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraCondensed.
        /// </summary>
        internal static string FontStretchExtraCondensed {
            get {
                return ResourceManager.GetString("FontStretchExtraCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraExpanded.
        /// </summary>
        internal static string FontStretchExtraExpanded {
            get {
                return ResourceManager.GetString("FontStretchExtraExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string FontStretchNormal {
            get {
                return ResourceManager.GetString("FontStretchNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        internal static string FontStretchProperty {
            get {
                return ResourceManager.GetString("FontStretchProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SemiCondensed.
        /// </summary>
        internal static string FontStretchSemiCondensed {
            get {
                return ResourceManager.GetString("FontStretchSemiCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SemiExpanded.
        /// </summary>
        internal static string FontStretchSemiExpanded {
            get {
                return ResourceManager.GetString("FontStretchSemiExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UltraCondensed.
        /// </summary>
        internal static string FontStretchUltraCondensed {
            get {
                return ResourceManager.GetString("FontStretchUltraCondensed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UltraExpanded.
        /// </summary>
        internal static string FontStretchUltraExpanded {
            get {
                return ResourceManager.GetString("FontStretchUltraExpanded", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string FontStyleItalic {
            get {
                return ResourceManager.GetString("FontStyleItalic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string FontStyleNormal {
            get {
                return ResourceManager.GetString("FontStyleNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oblique.
        /// </summary>
        internal static string FontStyleOblique {
            get {
                return ResourceManager.GetString("FontStyleOblique", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string FontStyleProperty {
            get {
                return ResourceManager.GetString("FontStyleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string FontVariantNormal {
            get {
                return ResourceManager.GetString("FontVariantNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Variant.
        /// </summary>
        internal static string FontVariantProperty {
            get {
                return ResourceManager.GetString("FontVariantProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscript.
        /// </summary>
        internal static string FontVariantSubscript {
            get {
                return ResourceManager.GetString("FontVariantSubscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Superscript.
        /// </summary>
        internal static string FontVariantSuperscript {
            get {
                return ResourceManager.GetString("FontVariantSuperscript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bold.
        /// </summary>
        internal static string FontWeightBold {
            get {
                return ResourceManager.GetString("FontWeightBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraBold.
        /// </summary>
        internal static string FontWeightExtraBold {
            get {
                return ResourceManager.GetString("FontWeightExtraBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ExtraLight.
        /// </summary>
        internal static string FontWeightExtraLight {
            get {
                return ResourceManager.GetString("FontWeightExtraLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Light.
        /// </summary>
        internal static string FontWeightLight {
            get {
                return ResourceManager.GetString("FontWeightLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string FontWeightMedium {
            get {
                return ResourceManager.GetString("FontWeightMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string FontWeightNormal {
            get {
                return ResourceManager.GetString("FontWeightNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Weight.
        /// </summary>
        internal static string FontWeightProperty {
            get {
                return ResourceManager.GetString("FontWeightProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SemiBold.
        /// </summary>
        internal static string FontWeightSemiBold {
            get {
                return ResourceManager.GetString("FontWeightSemiBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UltraBold.
        /// </summary>
        internal static string FontWeightUltraBold {
            get {
                return ResourceManager.GetString("FontWeightUltraBold", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UltraLight.
        /// </summary>
        internal static string FontWeightUltraLight {
            get {
                return ResourceManager.GetString("FontWeightUltraLight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Foreground.
        /// </summary>
        internal static string ForegroundProperty {
            get {
                return ResourceManager.GetString("ForegroundProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General.
        /// </summary>
        internal static string GeneralFormatTabHeader {
            get {
                return ResourceManager.GetString("GeneralFormatTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hyperlink.
        /// </summary>
        internal static string Hyperlink {
            get {
                return ResourceManager.GetString("Hyperlink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reference.
        /// </summary>
        internal static string HyperlinkReferenceProperty {
            get {
                return ResourceManager.GetString("HyperlinkReferenceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceFormat.
        /// </summary>
        internal static string HyperlinkSourceFormatProperty {
            get {
                return ResourceManager.GetString("HyperlinkSourceFormatProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string Image {
            get {
                return ResourceManager.GetString("Image", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Image.
        /// </summary>
        internal static string ImageCategory {
            get {
                return ResourceManager.GetString("ImageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Data.
        /// </summary>
        internal static string ImageDataProperty {
            get {
                return ResourceManager.GetString("ImageDataProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotation.
        /// </summary>
        internal static string ImageRotationProperty {
            get {
                return ResourceManager.GetString("ImageRotationProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string ImageSizeProperty {
            get {
                return ResourceManager.GetString("ImageSizeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fill.
        /// </summary>
        internal static string ImageStretchFill {
            get {
                return ResourceManager.GetString("ImageStretchFill", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ImageStretchNone {
            get {
                return ResourceManager.GetString("ImageStretchNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stretch.
        /// </summary>
        internal static string ImageStretchProperty {
            get {
                return ResourceManager.GetString("ImageStretchProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uniform.
        /// </summary>
        internal static string ImageStretchUniform {
            get {
                return ResourceManager.GetString("ImageStretchUniform", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Import from File.
        /// </summary>
        internal static string Import {
            get {
                return ResourceManager.GetString("Import", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Inspect element.
        /// </summary>
        internal static string InspectElement {
            get {
                return ResourceManager.GetString("InspectElement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Italic.
        /// </summary>
        internal static string Italic {
            get {
                return ResourceManager.GetString("Italic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Layout.
        /// </summary>
        internal static string LayoutCategory {
            get {
                return ResourceManager.GetString("LayoutCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        internal static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LineBreak.
        /// </summary>
        internal static string LineBreak {
            get {
                return ResourceManager.GetString("LineBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string List {
            get {
                return ResourceManager.GetString("List", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List.
        /// </summary>
        internal static string ListCategory {
            get {
                return ResourceManager.GetString("ListCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Items.
        /// </summary>
        internal static string ListItems {
            get {
                return ResourceManager.GetString("ListItems", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ItemTemplate.
        /// </summary>
        internal static string ListItemTemplate {
            get {
                return ResourceManager.GetString("ListItemTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarkerOffset.
        /// </summary>
        internal static string ListMarkerOffset {
            get {
                return ResourceManager.GetString("ListMarkerOffset", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarkerOffsetSize.
        /// </summary>
        internal static string ListMarkerOffsetSizeProperty {
            get {
                return ResourceManager.GetString("ListMarkerOffsetSizeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarkerOffsetSizeUnit.
        /// </summary>
        internal static string ListMarkerOffsetSizeUnitProperty {
            get {
                return ResourceManager.GetString("ListMarkerOffsetSizeUnitProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Box.
        /// </summary>
        internal static string ListMarkerStyleBox {
            get {
                return ResourceManager.GetString("ListMarkerStyleBox", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Circle.
        /// </summary>
        internal static string ListMarkerStyleCircle {
            get {
                return ResourceManager.GetString("ListMarkerStyleCircle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decimal.
        /// </summary>
        internal static string ListMarkerStyleDecimal {
            get {
                return ResourceManager.GetString("ListMarkerStyleDecimal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Disc.
        /// </summary>
        internal static string ListMarkerStyleDisc {
            get {
                return ResourceManager.GetString("ListMarkerStyleDisc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LowerLatin.
        /// </summary>
        internal static string ListMarkerStyleLowerLatin {
            get {
                return ResourceManager.GetString("ListMarkerStyleLowerLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LowerRoman.
        /// </summary>
        internal static string ListMarkerStyleLowerRoman {
            get {
                return ResourceManager.GetString("ListMarkerStyleLowerRoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to None.
        /// </summary>
        internal static string ListMarkerStyleNone {
            get {
                return ResourceManager.GetString("ListMarkerStyleNone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MarkerStyle.
        /// </summary>
        internal static string ListMarkerStyleProperty {
            get {
                return ResourceManager.GetString("ListMarkerStyleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Square.
        /// </summary>
        internal static string ListMarkerStyleSquare {
            get {
                return ResourceManager.GetString("ListMarkerStyleSquare", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpperLatin.
        /// </summary>
        internal static string ListMarkerStyleUpperLatin {
            get {
                return ResourceManager.GetString("ListMarkerStyleUpperLatin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UpperRoman.
        /// </summary>
        internal static string ListMarkerStyleUpperRoman {
            get {
                return ResourceManager.GetString("ListMarkerStyleUpperRoman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StartIndex.
        /// </summary>
        internal static string ListStartIndexProperty {
            get {
                return ResourceManager.GetString("ListStartIndexProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Margin.
        /// </summary>
        internal static string MarginProperty {
            get {
                return ResourceManager.GetString("MarginProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Down.
        /// </summary>
        internal static string MoveDown {
            get {
                return ResourceManager.GetString("MoveDown", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Move Up.
        /// </summary>
        internal static string MoveUp {
            get {
                return ResourceManager.GetString("MoveUp", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        internal static string NameProperty {
            get {
                return ResourceManager.GetString("NameProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number, &apos;{0}&apos;.
        /// </summary>
        internal static string NumberFormat {
            get {
                return ResourceManager.GetString("NumberFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sample.
        /// </summary>
        internal static string NumberFormatSample {
            get {
                return ResourceManager.GetString("NumberFormatSample", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number.
        /// </summary>
        internal static string NumberFormatTabHeader {
            get {
                return ResourceManager.GetString("NumberFormatTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object, &apos;{0}&apos;.
        /// </summary>
        internal static string ObjectFormat {
            get {
                return ResourceManager.GetString("ObjectFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Object.
        /// </summary>
        internal static string ObjectFormatTabHeader {
            get {
                return ResourceManager.GetString("ObjectFormatTabHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        internal static string PaddingProperty {
            get {
                return ResourceManager.GetString("PaddingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageBreak.
        /// </summary>
        internal static string PageBreak {
            get {
                return ResourceManager.GetString("PageBreak", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        internal static string PageCategory {
            get {
                return ResourceManager.GetString("PageCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Padding.
        /// </summary>
        internal static string PagePaddingProperty {
            get {
                return ResourceManager.GetString("PagePaddingProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Size.
        /// </summary>
        internal static string PageSizeProperty {
            get {
                return ResourceManager.GetString("PageSizeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paragraph.
        /// </summary>
        internal static string Paragraph {
            get {
                return ResourceManager.GetString("Paragraph", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Indent.
        /// </summary>
        internal static string ParagraphIndent {
            get {
                return ResourceManager.GetString("ParagraphIndent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndentSize.
        /// </summary>
        internal static string ParagraphIndentSizeProperty {
            get {
                return ResourceManager.GetString("ParagraphIndentSizeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to IndentSizeUnit.
        /// </summary>
        internal static string ParagraphIndentSizeUnitProperty {
            get {
                return ResourceManager.GetString("ParagraphIndentSizeUnitProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Paste.
        /// </summary>
        internal static string Paste {
            get {
                return ResourceManager.GetString("Paste", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Preview.
        /// </summary>
        internal static string Preview {
            get {
                return ResourceManager.GetString("Preview", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string PrintElementPropertyDockPanel {
            get {
                return ResourceManager.GetString("PrintElementPropertyDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintView.
        /// </summary>
        internal static string PrintView {
            get {
                return ResourceManager.GetString("PrintView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blocks.
        /// </summary>
        internal static string PrintViewBlocks {
            get {
                return ResourceManager.GetString("PrintViewBlocks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PrintView.
        /// </summary>
        internal static string PrintViewDesignerName {
            get {
                return ResourceManager.GetString("PrintViewDesignerName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string PrintViewStyle {
            get {
                return ResourceManager.GetString("PrintViewStyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Properties.
        /// </summary>
        internal static string PrintViewStylePropertiesDockPanel {
            get {
                return ResourceManager.GetString("PrintViewStylePropertiesDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string PrintViewStyles {
            get {
                return ResourceManager.GetString("PrintViewStyles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string PrintViewStylesDockPanel {
            get {
                return ResourceManager.GetString("PrintViewStylesDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tree.
        /// </summary>
        internal static string PrintViewTreeDockPanel {
            get {
                return ResourceManager.GetString("PrintViewTreeDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Viewer.
        /// </summary>
        internal static string PrintViewViewerDockPanel {
            get {
                return ResourceManager.GetString("PrintViewViewerDockPanel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        internal static string PropertyEditorBarcodeQrErrorCorrectionHigh {
            get {
                return ResourceManager.GetString("PropertyEditorBarcodeQrErrorCorrectionHigh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        internal static string PropertyEditorBarcodeQrErrorCorrectionLow {
            get {
                return ResourceManager.GetString("PropertyEditorBarcodeQrErrorCorrectionLow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Medium.
        /// </summary>
        internal static string PropertyEditorBarcodeQrErrorCorrectionMedium {
            get {
                return ResourceManager.GetString("PropertyEditorBarcodeQrErrorCorrectionMedium", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quartile.
        /// </summary>
        internal static string PropertyEditorBarcodeQrErrorCorrectionQuartile {
            get {
                return ResourceManager.GetString("PropertyEditorBarcodeQrErrorCorrectionQuartile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Display Format.
        /// </summary>
        internal static string PropertyEditorDisplayFormatDialog {
            get {
                return ResourceManager.GetString("PropertyEditorDisplayFormatDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace current PrintView?.
        /// </summary>
        internal static string RelpaceCurrentPrintView {
            get {
                return ResourceManager.GetString("RelpaceCurrentPrintView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Replace content &apos;{0}&apos; on &apos;{1}&apos;?.
        /// </summary>
        internal static string ReplaceElementQuestion {
            get {
                return ResourceManager.GetString("ReplaceElementQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate0.
        /// </summary>
        internal static string RotationRotate0 {
            get {
                return ResourceManager.GetString("RotationRotate0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate180.
        /// </summary>
        internal static string RotationRotate180 {
            get {
                return ResourceManager.GetString("RotationRotate180", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate270.
        /// </summary>
        internal static string RotationRotate270 {
            get {
                return ResourceManager.GetString("RotationRotate270", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rotate90.
        /// </summary>
        internal static string RotationRotate90 {
            get {
                return ResourceManager.GetString("RotationRotate90", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Run.
        /// </summary>
        internal static string Run {
            get {
                return ResourceManager.GetString("Run", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SourceFormat.
        /// </summary>
        internal static string RunSourceFormatProperty {
            get {
                return ResourceManager.GetString("RunSourceFormatProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string RunTextProperty {
            get {
                return ResourceManager.GetString("RunTextProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Section.
        /// </summary>
        internal static string Section {
            get {
                return ResourceManager.GetString("Section", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowHeader.
        /// </summary>
        internal static string ShowHeaderProperty {
            get {
                return ResourceManager.GetString("ShowHeaderProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowText.
        /// </summary>
        internal static string ShowTextProperty {
            get {
                return ResourceManager.GetString("ShowTextProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Height.
        /// </summary>
        internal static string SizeHeightProperty {
            get {
                return ResourceManager.GetString("SizeHeightProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SizeUnit.
        /// </summary>
        internal static string SizeSizeUnitProperty {
            get {
                return ResourceManager.GetString("SizeSizeUnitProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cm.
        /// </summary>
        internal static string SizeUnitCm {
            get {
                return ResourceManager.GetString("SizeUnitCm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to In.
        /// </summary>
        internal static string SizeUnitIn {
            get {
                return ResourceManager.GetString("SizeUnitIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mm.
        /// </summary>
        internal static string SizeUnitMm {
            get {
                return ResourceManager.GetString("SizeUnitMm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pt.
        /// </summary>
        internal static string SizeUnitPt {
            get {
                return ResourceManager.GetString("SizeUnitPt", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Px.
        /// </summary>
        internal static string SizeUnitPx {
            get {
                return ResourceManager.GetString("SizeUnitPx", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Width.
        /// </summary>
        internal static string SizeWidthProperty {
            get {
                return ResourceManager.GetString("SizeWidthProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Expression.
        /// </summary>
        internal static string SourceExpression {
            get {
                return ResourceManager.GetString("SourceExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string SourceProperty {
            get {
                return ResourceManager.GetString("SourceProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Span.
        /// </summary>
        internal static string Span {
            get {
                return ResourceManager.GetString("Span", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Style.
        /// </summary>
        internal static string StyleProperty {
            get {
                return ResourceManager.GetString("StyleProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string StylesEditorDialog {
            get {
                return ResourceManager.GetString("StylesEditorDialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Styles.
        /// </summary>
        internal static string StylesProperty {
            get {
                return ResourceManager.GetString("StylesProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string Table {
            get {
                return ResourceManager.GetString("Table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Table.
        /// </summary>
        internal static string TableCategory {
            get {
                return ResourceManager.GetString("TableCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableCell.
        /// </summary>
        internal static string TableCell {
            get {
                return ResourceManager.GetString("TableCell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ColumnSpan.
        /// </summary>
        internal static string TableCellColumnSpanProperty {
            get {
                return ResourceManager.GetString("TableCellColumnSpanProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RowSpan.
        /// </summary>
        internal static string TableCellRowSpanProperty {
            get {
                return ResourceManager.GetString("TableCellRowSpanProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableColumn.
        /// </summary>
        internal static string TableColumn {
            get {
                return ResourceManager.GetString("TableColumn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CellTemplate.
        /// </summary>
        internal static string TableColumnCellTemplate {
            get {
                return ResourceManager.GetString("TableColumnCellTemplate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Header.
        /// </summary>
        internal static string TableColumnHeader {
            get {
                return ResourceManager.GetString("TableColumnHeader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Columns.
        /// </summary>
        internal static string TableColumns {
            get {
                return ResourceManager.GetString("TableColumns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to TableRow.
        /// </summary>
        internal static string TableRow {
            get {
                return ResourceManager.GetString("TableRow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rows.
        /// </summary>
        internal static string TableRows {
            get {
                return ResourceManager.GetString("TableRows", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Center.
        /// </summary>
        internal static string TextAlignmentCenter {
            get {
                return ResourceManager.GetString("TextAlignmentCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Justify.
        /// </summary>
        internal static string TextAlignmentJustify {
            get {
                return ResourceManager.GetString("TextAlignmentJustify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string TextAlignmentLeft {
            get {
                return ResourceManager.GetString("TextAlignmentLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Alignment.
        /// </summary>
        internal static string TextAlignmentProperty {
            get {
                return ResourceManager.GetString("TextAlignmentProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string TextAlignmentRight {
            get {
                return ResourceManager.GetString("TextAlignmentRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lowercase.
        /// </summary>
        internal static string TextCaseLowercase {
            get {
                return ResourceManager.GetString("TextCaseLowercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string TextCaseNormal {
            get {
                return ResourceManager.GetString("TextCaseNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Case.
        /// </summary>
        internal static string TextCaseProperty {
            get {
                return ResourceManager.GetString("TextCaseProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SentenceCase.
        /// </summary>
        internal static string TextCaseSentenceCase {
            get {
                return ResourceManager.GetString("TextCaseSentenceCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ToggleCase.
        /// </summary>
        internal static string TextCaseToggleCase {
            get {
                return ResourceManager.GetString("TextCaseToggleCase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Uppercase.
        /// </summary>
        internal static string TextCaseUppercase {
            get {
                return ResourceManager.GetString("TextCaseUppercase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Text.
        /// </summary>
        internal static string TextCategory {
            get {
                return ResourceManager.GetString("TextCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Normal.
        /// </summary>
        internal static string TextDecorationNormal {
            get {
                return ResourceManager.GetString("TextDecorationNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Overline.
        /// </summary>
        internal static string TextDecorationOverline {
            get {
                return ResourceManager.GetString("TextDecorationOverline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Decoration.
        /// </summary>
        internal static string TextDecorationProperty {
            get {
                return ResourceManager.GetString("TextDecorationProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Strikethrough.
        /// </summary>
        internal static string TextDecorationStrikethrough {
            get {
                return ResourceManager.GetString("TextDecorationStrikethrough", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string TextDecorationUnderline {
            get {
                return ResourceManager.GetString("TextDecorationUnderline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        internal static string ThicknessAllProperty {
            get {
                return ResourceManager.GetString("ThicknessAllProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bottom.
        /// </summary>
        internal static string ThicknessBottomProperty {
            get {
                return ResourceManager.GetString("ThicknessBottomProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Left.
        /// </summary>
        internal static string ThicknessLeftProperty {
            get {
                return ResourceManager.GetString("ThicknessLeftProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Right.
        /// </summary>
        internal static string ThicknessRightProperty {
            get {
                return ResourceManager.GetString("ThicknessRightProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SizeUnit.
        /// </summary>
        internal static string ThicknessSizeUnitProperty {
            get {
                return ResourceManager.GetString("ThicknessSizeUnitProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Top.
        /// </summary>
        internal static string ThicknessTopProperty {
            get {
                return ResourceManager.GetString("ThicknessTopProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Underline.
        /// </summary>
        internal static string Underline {
            get {
                return ResourceManager.GetString("Underline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ListView.
        /// </summary>
        internal static string ViewTypeListView {
            get {
                return ResourceManager.GetString("ViewTypeListView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ObjectView.
        /// </summary>
        internal static string ViewTypeObjectView {
            get {
                return ResourceManager.GetString("ViewTypeObjectView", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ViewType.
        /// </summary>
        internal static string ViewTypeProperty {
            get {
                return ResourceManager.GetString("ViewTypeProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Always.
        /// </summary>
        internal static string VisibilityAlways {
            get {
                return ResourceManager.GetString("VisibilityAlways", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Never.
        /// </summary>
        internal static string VisibilityNever {
            get {
                return ResourceManager.GetString("VisibilityNever", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visibility.
        /// </summary>
        internal static string VisibilityProperty {
            get {
                return ResourceManager.GetString("VisibilityProperty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source.
        /// </summary>
        internal static string VisibilitySource {
            get {
                return ResourceManager.GetString("VisibilitySource", resourceCulture);
            }
        }
    }
}
