//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.SystemConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.SystemConfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionUnit completed with error..
        /// </summary>
        internal static string ActionUnitCompletedWithError {
            get {
                return ResourceManager.GetString("ActionUnitCompletedWithError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActionUnit is not registered..
        /// </summary>
        internal static string ActionUnitIsNotRegistered {
            get {
                return ResourceManager.GetString("ActionUnitIsNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add unsaved user to role..
        /// </summary>
        internal static string CantAddUnsavedUserToRole {
            get {
                return ResourceManager.GetString("CantAddUnsavedUserToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove unsaved user from role..
        /// </summary>
        internal static string CantRemoveUnsavedUserFromRole {
            get {
                return ResourceManager.GetString("CantRemoveUnsavedUserFromRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing on UserStorage cache....
        /// </summary>
        internal static string SubscribingOnUserStorageCache {
            get {
                return ResourceManager.GetString("SubscribingOnUserStorageCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing on UserStorage cache has successfuly completed..
        /// </summary>
        internal static string SubscribingOnUserStorageCacheHasCompleted {
            get {
                return ResourceManager.GetString("SubscribingOnUserStorageCacheHasCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing on UserStorage cache has completed with error..
        /// </summary>
        internal static string SubscribingOnUserStorageCacheHasCompletedWithError {
            get {
                return ResourceManager.GetString("SubscribingOnUserStorageCacheHasCompletedWithError", resourceCulture);
            }
        }
    }
}
