//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.SystemConfig.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.SystemConfig.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob storage already created..
        /// </summary>
        internal static string BlobStorageAlreadyCreated {
            get {
                return ResourceManager.GetString("BlobStorageAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Blob storage created..
        /// </summary>
        internal static string BlobStorageCreated {
            get {
                return ResourceManager.GetString("BlobStorageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot run test server..
        /// </summary>
        internal static string CannotStartTestServer {
            get {
                return ResourceManager.GetString("CannotStartTestServer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add unsaved user to role..
        /// </summary>
        internal static string CantAddUnsavedUserToRole {
            get {
                return ResourceManager.GetString("CantAddUnsavedUserToRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t remove unsaved user from role..
        /// </summary>
        internal static string CantRemoveUnsavedUserFromRole {
            get {
                return ResourceManager.GetString("CantRemoveUnsavedUserFromRole", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Claim with type &apos;{0}&apos; has user linked and should not be deleted..
        /// </summary>
        internal static string ClaimIsUsed {
            get {
                return ResourceManager.GetString("ClaimIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User claim not found: &apos;{0}&apos;..
        /// </summary>
        internal static string ClaimNotFound {
            get {
                return ResourceManager.GetString("ClaimNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration created: {0}.
        /// </summary>
        internal static string ConfigurationCreated {
            get {
                return ResourceManager.GetString("ConfigurationCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration {0} not found in: {1}. See AppSettings.ConfigurationPath setting and set to directory where config files stored..
        /// </summary>
        internal static string ConfigurationFileNotFound {
            get {
                return ResourceManager.GetString("ConfigurationFileNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Need to specify ConfigurationId to set configuration from JSON..
        /// </summary>
        internal static string ConfigurationIdNotFound {
            get {
                return ResourceManager.GetString("ConfigurationIdNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to configuration version not found in repository: &apos;{0}&apos;..
        /// </summary>
        internal static string ConfigurationVersionNotFound {
            get {
                return ResourceManager.GetString("ConfigurationVersionNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration version for update should be specified..
        /// </summary>
        internal static string ConfigurationVersionShouldSpecified {
            get {
                return ResourceManager.GetString("ConfigurationVersionShouldSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action module not specified..
        /// </summary>
        internal static string ErrorActionModuleNotSpecified {
            get {
                return ResourceManager.GetString("ErrorActionModuleNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Action unit for generator not specified..
        /// </summary>
        internal static string ErrorActionUnitNotSpecified {
            get {
                return ResourceManager.GetString("ErrorActionUnitNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration name not found..
        /// </summary>
        internal static string ErrorConfigurationNameNotFound {
            get {
                return ResourceManager.GetString("ErrorConfigurationNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Created generator name not specified..
        /// </summary>
        internal static string ErrorCreatedGeneratorNameNotSpecified {
            get {
                return ResourceManager.GetString("ErrorCreatedGeneratorNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name of document metadata element not specified..
        /// </summary>
        internal static string ErrorDocumentMetadataElementNameNotSpecified {
            get {
                return ResourceManager.GetString("ErrorDocumentMetadataElementNameNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generator metadata type not specified..
        /// </summary>
        internal static string ErrorGeneratorMetadataTypeNotSpecified {
            get {
                return ResourceManager.GetString("ErrorGeneratorMetadataTypeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Source metadata for generator not specified..
        /// </summary>
        internal static string ErrorMetadataGeneratorNotSpecified {
            get {
                return ResourceManager.GetString("ErrorMetadataGeneratorNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Item metadata not specified..
        /// </summary>
        internal static string ErrorMetadataNotSpecified {
            get {
                return ResourceManager.GetString("ErrorMetadataNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata type not specified..
        /// </summary>
        internal static string ErrorMetadataTypeNotSpecified {
            get {
                return ResourceManager.GetString("ErrorMetadataTypeNotSpecified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error in parsing JSON configuration..
        /// </summary>
        internal static string ErrorParsingJsonConfiguration {
            get {
                return ResourceManager.GetString("ErrorParsingJsonConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event storage already created..
        /// </summary>
        internal static string EventStorageAlreadyCreated {
            get {
                return ResourceManager.GetString("EventStorageAlreadyCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Event storage created..
        /// </summary>
        internal static string EventStorageCreated {
            get {
                return ResourceManager.GetString("EventStorageCreated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata for generator &apos;{0}&apos; not found..
        /// </summary>
        internal static string GeneratorMetadataNotFound {
            get {
                return ResourceManager.GetString("GeneratorMetadataNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to generator metadata with name &apos;{0}&apos; not registered..
        /// </summary>
        internal static string GeneratorMetadataNotRegistered {
            get {
                return ResourceManager.GetString("GeneratorMetadataNotRegistered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Metadata object successfully deleted..
        /// </summary>
        internal static string MetadataObjectDeleted {
            get {
                return ResourceManager.GetString("MetadataObjectDeleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to metadata object successfully updated.
        /// </summary>
        internal static string MetadataObjectSuccessfullyUpdated {
            get {
                return ResourceManager.GetString("MetadataObjectSuccessfullyUpdated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified register &apos;{0}&apos; not found.
        /// </summary>
        internal static string RegisterNotFound {
            get {
                return ResourceManager.GetString("RegisterNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with name &apos;{0}&apos; has user linked and should not be deleted..
        /// </summary>
        internal static string RoleIsUsed {
            get {
                return ResourceManager.GetString("RoleIsUsed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Role with name &apos;{0}&apos; not found..
        /// </summary>
        internal static string RoleNotFound {
            get {
                return ResourceManager.GetString("RoleNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuration with specified name not found: &apos;{0}&apos;..
        /// </summary>
        internal static string SpecifiedConfigurationNameNotFound {
            get {
                return ResourceManager.GetString("SpecifiedConfigurationNameNotFound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified interval &apos;{0}&apos; is invalid. Supported intervals: year, quarter, month, week, day, hour, minute, second..
        /// </summary>
        internal static string SpecifiedIntervalIsInvalidSupportedIntervals {
            get {
                return ResourceManager.GetString("SpecifiedIntervalIsInvalidSupportedIntervals", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Specified timezone {0} is invalid. Valid timezone example: &apos;+05:00&apos;..
        /// </summary>
        internal static string SpecifiedTimezoneIsInvalid {
            get {
                return ResourceManager.GetString("SpecifiedTimezoneIsInvalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing on UserStorage cache....
        /// </summary>
        internal static string SubscribingOnUserStorageCache {
            get {
                return ResourceManager.GetString("SubscribingOnUserStorageCache", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing on UserStorage cache has successfuly completed..
        /// </summary>
        internal static string SubscribingOnUserStorageCacheHasCompleted {
            get {
                return ResourceManager.GetString("SubscribingOnUserStorageCacheHasCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribing on UserStorage cache has completed with error..
        /// </summary>
        internal static string SubscribingOnUserStorageCacheHasCompletedWithError {
            get {
                return ResourceManager.GetString("SubscribingOnUserStorageCacheHasCompletedWithError", resourceCulture);
            }
        }
    }
}
