//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

using System.Reflection;

namespace InfinniPlatform.DocumentStorage.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.DocumentStorage.Properties.Resources", typeof(Resources).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the document storage for type completed with exception..
        /// </summary>
        internal static string CreatingDocumentStorageForTypeCompletedWithException {
            get {
                return ResourceManager.GetString("CreatingDocumentStorageForTypeCompletedWithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the document storage for type started..
        /// </summary>
        internal static string CreatingDocumentStorageForTypeStarted {
            get {
                return ResourceManager.GetString("CreatingDocumentStorageForTypeStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the document storage for type successfully completed..
        /// </summary>
        internal static string CreatingDocumentStorageForTypeSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("CreatingDocumentStorageForTypeSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the document storage started..
        /// </summary>
        internal static string CreatingDocumentStorageStarted {
            get {
                return ResourceManager.GetString("CreatingDocumentStorageStarted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Creating the document storage successfully completed..
        /// </summary>
        internal static string CreatingDocumentStorageSuccessfullyCompleted {
            get {
                return ResourceManager.GetString("CreatingDocumentStorageSuccessfullyCompleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Function {0}() is not supported..
        /// </summary>
        internal static string FunctionIsNotSupported {
            get {
                return ResourceManager.GetString("FunctionIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal symbol &apos;{0}&apos; in expression. Index: {1}..
        /// </summary>
        internal static string IllegalSymbolInExpression {
            get {
                return ResourceManager.GetString("IllegalSymbolInExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Illegal token &apos;{0}&apos;..
        /// </summary>
        internal static string IllegalToken {
            get {
                return ResourceManager.GetString("IllegalToken", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incomplete expression..
        /// </summary>
        internal static string IncompleteExpression {
            get {
                return ResourceManager.GetString("IncompleteExpression", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method not allowed..
        /// </summary>
        internal static string MethodNotAllowed {
            get {
                return ResourceManager.GetString("MethodNotAllowed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request processed with exception..
        /// </summary>
        internal static string RequestProcessedWithException {
            get {
                return ResourceManager.GetString("RequestProcessedWithException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string TokenIsNotSupported {
            get {
                return ResourceManager.GetString("TokenIsNotSupported", resourceCulture);
            }
        }
    }
}
