//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.Owin.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.Owin.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot start service correctly..
        /// </summary>
        internal static string CannotStartServiceCorrectly {
            get {
                return ResourceManager.GetString("CannotStartServiceCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot stop service correctly..
        /// </summary>
        internal static string CannotStopServiceCorrectly {
            get {
                return ResourceManager.GetString("CannotStopServiceCorrectly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Method &apos;HTTP {0} {1}&apos; is not supported..
        /// </summary>
        internal static string MethodIsNotSupported {
            get {
                return ResourceManager.GetString("MethodIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request body cannot be null..
        /// </summary>
        internal static string RequestBodyCannotBeNull {
            get {
                return ResourceManager.GetString("RequestBodyCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request has unsupported content type &apos;{0}&apos;..
        /// </summary>
        internal static string RequestHasUnsupportedContentType {
            get {
                return ResourceManager.GetString("RequestHasUnsupportedContentType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Request processing completed with unexpected exception..
        /// </summary>
        internal static string RequestProcessingCompletedWithUnexpectedException {
            get {
                return ResourceManager.GetString("RequestProcessingCompletedWithUnexpectedException", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server certificate cannot be null or whitespace when using &apos;https&apos; scheme..
        /// </summary>
        internal static string ServerCertificateCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ServerCertificateCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server certificate &apos;{0}&apos; cannot bind on port &apos;{1}&apos;..
        /// </summary>
        internal static string ServerCertificateCannotBindOnPort {
            get {
                return ResourceManager.GetString("ServerCertificateCannotBindOnPort", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server hosting configuration cannot be null..
        /// </summary>
        internal static string ServerConfigurationCannotBeNull {
            get {
                return ResourceManager.GetString("ServerConfigurationCannotBeNull", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name cannot be null or whitespace..
        /// </summary>
        internal static string ServerNameCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ServerNameCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server name &apos;{0}&apos; is not local address..
        /// </summary>
        internal static string ServerNameIsNotLocal {
            get {
                return ResourceManager.GetString("ServerNameIsNotLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server port &apos;{0}&apos; is incorrect. Server port should be more than zero..
        /// </summary>
        internal static string ServerPortIsIncorrect {
            get {
                return ResourceManager.GetString("ServerPortIsIncorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server scheme cannot be null or whitespace..
        /// </summary>
        internal static string ServerSchemeCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ServerSchemeCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Server scheme &apos;{0}&apos; is not supported. Use &apos;http&apos; or &apos;https&apos;..
        /// </summary>
        internal static string ServerSchemeIsNotSupported {
            get {
                return ResourceManager.GetString("ServerSchemeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Serving static content..
        /// </summary>
        internal static string ServingStaticContent {
            get {
                return ResourceManager.GetString("ServingStaticContent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unhandled exception.
        /// </summary>
        internal static string UnhandledExceptionOwinMiddleware {
            get {
                return ResourceManager.GetString("UnhandledExceptionOwinMiddleware", resourceCulture);
            }
        }
    }
}
