//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18034
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InfinniPlatform.MessageQueue.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("InfinniPlatform.MessageQueue.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address cannot be null or white space..
        /// </summary>
        internal static string AddressCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("AddressCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Address should be absolute URI to HTTP or HTTPS service..
        /// </summary>
        internal static string AddressShouldBeAbsoluteUriToHttpOrHttpsService {
            get {
                return ResourceManager.GetString("AddressShouldBeAbsoluteUriToHttpOrHttpsService", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Consumer identifier cannot be null or white space..
        /// </summary>
        internal static string ConsumerIdCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ConsumerIdCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange name cannot be null or white space..
        /// </summary>
        internal static string ExchangeNameCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ExchangeNameCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange type cannot be null or white space..
        /// </summary>
        internal static string ExchangeTypeCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("ExchangeTypeCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Incorrect security token..
        /// </summary>
        internal static string IntegrationBusSecurityTokenIsNotValid {
            get {
                return ResourceManager.GetString("IntegrationBusSecurityTokenIsNotValid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Queue name cannot be null or white space..
        /// </summary>
        internal static string QueueNameCannotBeNullOrWhiteSpace {
            get {
                return ResourceManager.GetString("QueueNameCannotBeNullOrWhiteSpace", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Exchange type &apos;{0}&apos; is not supported..
        /// </summary>
        internal static string SpecifiedExchangeTypeIsNotSupported {
            get {
                return ResourceManager.GetString("SpecifiedExchangeTypeIsNotSupported", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Service &apos;{0}&apos; is not available..
        /// </summary>
        internal static string SubscriptionServiceIsNotAvailable {
            get {
                return ResourceManager.GetString("SubscriptionServiceIsNotAvailable", resourceCulture);
            }
        }
    }
}
